### PR TITLE
Start developing plugin v7.0

### PR DESCRIPTION
**Pull request by charlesakalugwu**
```release-note
NONE
```

### CODE REVIEW

**Comment by charlesakalugwu** [comment]
unit failure: i updated the hashes and should be all good now

**Comment by charlesakalugwu** [comment]
This PR is pending the release of the new image on the partner portal

**Comment by charlesakalugwu** [comment]
upgrade-v5.2 flake #661

**Comment by ehashman** [comment]
@charlesakalugwu you mentioned on standup yesterday that you wrote some scripts to help automate the release process; are those included in this PR or elsewhere?

**Comment by mjudeikis** [comment]
look good!!! remove hold when the image is published 
/hold
/lgtm

**Comment by ehashman** [comment]
/retest
flake #1695

**Comment by ehashman** [comment]
/hold cancel

images published.

**Pull request merged**
