### PR TITLE
Enable cloud API rate limiting for nodes

### LINKED ISSUE #1480: enable node api rate limiting
See the suggestions at https://github.com/Azure/aks-engine/blob/master/docs/howto/kubernetes-large-clusters.md

@asalkeld I think I'm prepared to apply the cloudprovider settings from above on a suck it and see basis - I'm less sure I want to apply the kubelet and controller settings until we are definitely running into problems.  WDYT?

### PR DESCRIPTION
**Pull request by ehashman**
```release-note
Enable cloud API rate limiting for nodes
```

Closes #1480.

### CODE REVIEW

**Comment by ehashman** [comment]
I've tried testing this locally but I seem to be getting an unrelated test failure so leaving this as WIP for now:

```
--- FAIL: TestHashScaleSetStability (0.06s)
    hash_test.go:138: v3.2: master: hash changed to 86304d2f7ac99b1847153a69f97d0247b64b11825d9f7c89bd5dff7717844d14
    hash_test.go:138: v3.2: infra: hash changed to 5c6da53fd4acc534f6da0be6ceb9e3ba982b841ee3214ab38af132d4774c3d52
    hash_test.go:138: v3.2: compute: hash changed to 76d146f812643321ffe7d88f5659175cb0a7817ddab1e76e11a2b39b06f74669
    hash_test.go:138: v4.2: master: hash changed to 20b5c651af26a12c29adc7a3e2ca701457c62b9d41142663e0d5bf2e7b15c756
    hash_test.go:138: v4.2: infra: hash changed to df4f7869f72b5f1ff412582c8b281379d41cc592bb981299cbab2d16fbda05e2
    hash_test.go:138: v4.2: compute: hash changed to 30f91412ca00006fc4ceb58d2a9ba7c8428222a0db381e5148de8c68d221519b
```

**Comment by jim-minter** [comment]
you've got a problem with the version of gobindata you're using - use commit 41975c0

**Comment by ehashman** [comment]
@jim-minter the less-than-elegant fix got all the tests passing so I think this is GTG, let me know if you want me to go for a more full refactor in this or a follow-up PR?

**Pull request merged**
