### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by ross-bryan**
rm inactive

````release-note
NONE
````

### CODE REVIEW

**Review by s-amann — APPROVED** [review]

**Review by petrkotas — APPROVED** [review]
Thanks!

**Review by m1kola — APPROVED** [review]

**Comment by m1kola** [comment]
Thanks updating it. Could you please add the following to the description? I can not edit it. 

```release-note
NONE
```

**Review by mjudeikis — APPROVED** [review]

**Review by bennerv — APPROVED** [review]
:shipit:

**Pull request closed without merging**
