### PR TITLE
replace hack/aad.sh with a go binary

### PR DESCRIPTION
**Pull request by asalkeld**
This replaces the shell script with a go binary.

### CODE REVIEW

**Comment by mjudeikis** [comment]
@asalkeld we need to update `create.sh` because it is calling `aad.sh` to do an `app-update`

**Comment by asalkeld** [comment]
@mjudeikis  I don't see where: https://github.com/openshift/openshift-azure/blob/master/hack/create.sh

**Comment by mjudeikis** [comment]
> @mjudeikis I don't see where: https://github.com/openshift/openshift-azure/blob/master/hack/create.sh

Sorry, my bad. need rebase local copy :D

**Comment by mjudeikis** [comment]
lgtm,
will wait for the second review

**Comment by mjudeikis** [comment]
on the other hand. Not sure if we should do this. shell scripts are much easier to maintain. And our RP already does what's needed with the previous PR.

@jim-minter @kargakis  WDYT?

**Comment by kargakis** [comment]
I am happy with the state of the fake rp, don't really care about removing
the scripts.

**Pull request closed without merging**
