### PR TITLE
add etcd template 

### PR DESCRIPTION
**Pull request by mjudeikis**
Template etcd config. Want to know if this is feasible as we need something like this so we could start modifying configuration from the code. One example is a different number of masters/etcd needs this.

ptal: @openshift/sig-azure

### CODE REVIEW

**Comment by kargakis** [comment]
Related: https://github.com/openshift/openshift-azure/issues/212

**Comment by jim-minter** [comment]
I'm not sure about this but I can't help but think it's taking us in the wrong direction.

**Comment by mjudeikis** [comment]
What do you have in mind for this? We need to make master script smaller and code manageable?

**Comment by jim-minter** [comment]
I'm not saying never but I'm convinced this is overkill right now.

**Pull request closed without merging**
