### PR TITLE
removing ansible repo

### PR DESCRIPTION
**Pull request by gburges**
Not needed anymore

```release-note
NONE
```

### CODE REVIEW

**Comment by jim-minter** [comment]
and there was much rejoicing!

**Comment by jim-minter** [comment]
/lgtm
/hold
hold cancel once vmimage test passes

**Comment by thekad** [comment]
needs `make generate` ?

**Comment by jim-minter** [comment]
/test vmimage
/lgtm
hold cancel once vmimage test passes

**Comment by jim-minter** [comment]
/test vmimage
/retest

issues #1102 #1540 #1336

**Comment by mjudeikis** [comment]
https://github.com/openshift/openshift-azure/issues/1336 https://github.com/openshift/openshift-azure/issues/1102
/retest

**Comment by mjudeikis** [comment]
/retest 
https://github.com/openshift/openshift-azure/issues/1545

**Comment by jim-minter** [comment]
vmimage passed, merging

**Pull request merged**
