### PR TITLE
sdn update policy change

### PR DESCRIPTION
**Pull request by mjudeikis**
Change SDN/OVS update policyt to `onUpdate`.

This should eliminate cluster-wide downtime and make it node specific only.

### CODE REVIEW

**Comment by jim-minter** [comment]
does this rotate the sdn correctly on masters?

**Comment by mjudeikis** [comment]
/hold
until we validate behaviour on master

**Comment by mjudeikis** [comment]
Broken due to:
```
	case "DaemonSet.apps":
		jsonpath.MustCompile("$.spec.revisionHistoryLimit").DeleteIfMatch(o.Object, int64(10))

		for _, c := range jsonpath.MustCompile("$.spec.template.spec").Get(o.Object) {
			defaultPodSpec(c.(map[string]interface{}))
		}

		jsonpath.MustCompile("$.spec.updateStrategy.rollingUpdate.maxUnavailable").DeleteIfMatch(o.Object, int64(1))
		jsonpath.MustCompile("$.spec.updateStrategy.rollingUpdate").DeleteIfMatch(o.Object, map[string]interface{}{})
		jsonpath.MustCompile("$.spec.updateStrategy.type").DeleteIfMatch(o.Object, "RollingUpdate")
		jsonpath.MustCompile("$.spec.updateStrategy").DeleteIfMatch(o.Object, map[string]interface{}{})
```

need rework :/

**Comment by jim-minter** [comment]
why is it broken?  I don't understand.

**Comment by mjudeikis** [comment]
> why is it broken? I don't understand.

False alarm. Was little bit too late in the evening for debugging. Looks like master behaves fine with this policy.

**Comment by jim-minter** [comment]
/hold
/lgtm

@mjudeikis unhold if you want this to merge

**Pull request merged**
