### PR TITLE
Create release v6.0 with pluginconfig and changelog

### PR DESCRIPTION
**Pull request by charlesakalugwu**
Create release v6.0 with updated pluginconfig and changelog

```release-note
NONE
```
**Image Name for v6.0 release**: rhel7-3.11-201907191212
**Disk version**: 311.117.20190719

### CODE REVIEW

**Comment by charlesakalugwu** [comment]
This is still pending the image build and release. Once that is done, the `imageVersion` will be updated and this PR can be moved from `draft`  status.

**Comment by ehashman** [comment]
Can we base this branch on decb8388c33e4aa4f2f6e33d81d6588ebe96ba6b instead of f9f0d403e69e73b91fa9be7a518a5daea4efa641?

**Comment by charlesakalugwu** [comment]
e2e-create failure is due to `redhat:osa:osa_311:311.117.20190719` image not yet being published
holding this for now. unhold after successful publish of `redhat:osa:osa_311:311.117.20190719` and excute `/retest e2e-create`
/hold

**Comment by ehashman** [comment]
/retest
flake #1481

**Comment by ehashman** [comment]
e2e-create succeeded, image is available

/hold cancel

**Pull request merged**
