### PR TITLE
don't set PrivateAPIServer on in v10 fakerp

### PR DESCRIPTION
**Pull request by jim-minter**
```release-note
NONE
```

### CODE REVIEW

**Comment by jim-minter** [comment]
cf https://github.com/openshift/release/pull/5580
plan: get this merged, tag it to v10.1.1, merge ^

**Comment by jim-minter** [comment]
@ehashman @mjudeikis @asalkeld fyi

**Comment by ehashman** [comment]
flake #552 

/test e2e-scaleupdown-v7.1

We'll have to override upgrade-v10.0

**Comment by ehashman** [comment]
Tagged.

**Pull request merged**
