### PR TITLE
 Remove configurables for derived CIs:

### PR DESCRIPTION
**Pull request by jim-minter**
- ImageResourceGroup
- ImageResourceName
- ImageConfigFormat
- MasterLBCNamePrefix
- CloudProviderConf

### CODE REVIEW

**Comment by jim-minter** [comment]
First commit is on its own in #413.

I'm leaving config fields in on the following basis:
- if they are uniquely derived during generate (e.g. certs, random secrets), OR
- if we want to latch their values to handle changing them on a timescale we choose (e.g. all the image pullspecs)

On that basis, we should remove the kubeconfigs.  This is a temptation because they are fully derivable and they bloat the config object a lot.  My concern is that it makes it a little harder to generate an admin kubeconfig from the config blob.  Q1: @kargakis @mjudeikis @pweil- wdyt what's your take on this?

Q2: should we do a `Images ImageConfig` to match `Certificates CertificateConfig` for PP?  Thoughts?

**Comment by jim-minter** [comment]
hmm, if we got rid of the kubeconfigs we'd be able to avoid pulling in all the kubernetes api in our api package.  More temptation.

**Comment by jim-minter** [comment]
cf #157

**Comment by mjudeikis** [comment]
I like the idea. Im up for `Images ImageConfig`. 
/test e2e

**Comment by jim-minter** [comment]
follow-up in #440

**Comment by jim-minter** [comment]
@kargakis points out there's a third category of config field which is required not to be derived: anything dependent on ENV vars which runs in the sync pod.

**Pull request merged**
