### PR TITLE
fix image build

### PR DESCRIPTION
**Pull request by mjudeikis**
```release-note
NONE
```

Remove exit to continue with the script

/cc @charlesakalugwu @kwoodson

### CODE REVIEW

**Comment by kwoodson** [comment]
@mjudeikis These failures are unrelated.  10 passed 1 failed.

/test vmimage

**Comment by thekad** [comment]
/test vmimage
flake already in openshift/openshift-azure#1616

**Comment by charlesakalugwu** [comment]
vmimage flake #1616 
/retest

**Comment by mjudeikis** [comment]
/test vmimage
im trying to suspect this is not a flake but a concequence of the image hardening...

**Comment by mjudeikis** [comment]
@kwoodson can you check if this is hardening impact?

**Comment by kwoodson** [comment]
@mjudeikis 

It appears that it could not mount the azure file storage:
```
Jul 02 16:08:27 compute-1562081346-000000 atomic-openshift-node[12981]: Mounting command: systemd-run
Jul 02 16:08:27 compute-1562081346-000000 atomic-openshift-node[12981]: Mounting arguments: --description=Kubernetes transient mount for /var/lib/origin/openshift.local.volumes/pods/9fb8b52c-9ce3-11e9-b8e7-000d3a1a5bf2/volumes/kubernetes.io~azure-file/pvc-9fa54729-9ce3-11e9-8c7f-000d3a1afc4a --scope -- mount -t cifs -o dir_mode=0777,file_mode=0777,username=<removed>,password=<removed>,vers=3.0,gid=1000310000 //safil1qkwegkwcyplkvt1zqp.file.core.windows.net/kubernetes-dynamic-pvc-9fa54729-9ce3-11e9-8c7f-000d3a1afc4a /var/lib/origin/openshift.local.volumes/pods/9fb8b52c-9ce3-11e9-b8e7-000d3a1a5bf2/volumes/kubernetes.io~azure-file/pvc-9fa54729-9ce3-11e9-8c7f-000d3a1afc4a
Jul 02 16:08:27 compute-1562081346-000000 atomic-openshift-node[12981]: Output: Running scope as unit run-30973.scope.
Jul 02 16:08:27 compute-1562081346-000000 atomic-openshift-node[12981]: mount error(2): No such file or directory
Jul 02 16:08:27 compute-1562081346-000000 atomic-openshift-node[12981]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

```

**Comment by kwoodson** [comment]
@mjudeikis https://github.com/openshift/openshift-azure/issues/1772

**Comment by ehashman** [comment]
/hold

I think #1773 will supersede this PR.

**Comment by kwoodson** [comment]
closing in favor of #1773

**Pull request closed without merging**
