### PR TITLE
Allowing annotation openshift.io/reconcile-protect=true instead of a label

### PR DESCRIPTION
**Pull request by Makdaam**
```release-note
Fixes bug which prevented adding reconcile-protect annotation to SCCs
```

### CODE REVIEW

**Comment by jim-minter** [comment]
@Makdaam good catch, thanks.
Please work with @ehashman to make sure this gets backported and sent to MSFT, they are still in the process of vendoring it

/lgtm

**Comment by Makdaam** [comment]
/test e2e-create-20191027-private
azure keyvault creation timed out flake this time

**Pull request merged**
