### PR TITLE
Ensure unlink command always exits with status code 0

### LINKED ISSUE #731: Compute scale set CSE script is being re-executed on scale up
We ran into an issue where it appeared that the node startup scripts were being reapplied to the vms upon update. 

We've been under the understanding that these scripts are run only once the first time a VM is created and never again.

We encountered this issue when developing key rotation e2e tests.

```
VM has reported a failure when processing extension 'cse'. Error message: "Enable failed: failed to execute command: command terminated with exit status=1 [stdout] [stderr] + SERVICE_TYPE=origin + '[' -f /etc/sysconfig/atomic-openshift-node ']' + SERVICE_TYPE=atomic-openshift + unlink /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt unlink: cannot unlink '/etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt': No such file or directory ".
```

@jim-minter @kargakis

### PR DESCRIPTION
**Pull request by charlesakalugwu**
Without this change, the compute scaleset becomes unhealthy during an update due to the missing link.

closes #731

### CODE REVIEW

**Comment by jim-minter** [comment]
/hold

We really need to understand why this is happening rather than papering over it.

**Comment by kargakis** [comment]
> We really need to understand why this is happening rather than papering over it.

My take too

**Comment by charlesakalugwu** [comment]
@jim-minter @kargakis i'm seeing the same issue when performing a basic scale up/down. 

```
=== RUN   TestE2eRealRP
Scale Out/In E2E tests starting, git commit unknown
Running Suite: Scale Out/In E2E Suite
=====================================
Random Seed: 1542891143
Will run 6 of 6 specs

Creating a cluster using the fake resource provider
Scale Out/In E2E tests [Fake] [Real] [Update] 
  should scale out the compute scale set to 2 vms
  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/suites/scaleupdown/spec.go:33
STEP: Parsing the external manifest
STEP: Updating the size of the compute scale set to 2 in the manifest
STEP: Calling update on the rp with the updated manifest
time="2018-11-22T13:52:23+01:00" level=info msg="convert to internal" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:52:23+01:00" level=info msg=enrich location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:52:23+01:00" level=info msg="read old config" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:52:23+01:00" level=info msg="merge old and new config" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:52:23+01:00" level=info msg="merging internal data models" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:52:23+01:00" level=info msg="validating internal data models" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:52:23+01:00" level=info msg="generating configs" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:52:23+01:00" level=info msg="persist config" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:52:23+01:00" level=info msg="generating arm templates" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:52:23+01:00" level=info msg="write helpers" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:52:23+01:00" level=info msg="starting update" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:52:24+01:00" level=info msg="applying arm template deployment" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:52:32+01:00" level=info msg="waiting for arm template deployment to complete" location=westeurope resourceGroup=charlesakalugwu-test

• Failure [38.379 seconds]
Scale Out/In E2E tests [Fake] [Real] [Update]
/home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/suites/scaleupdown/spec.go:26
  should scale out the compute scale set to 2 vms [It]
  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/suites/scaleupdown/spec.go:33

  Expected error:
      <*api.PluginError | 0xc420267760>: {
          Err: {Code: "", Message: "", Target: nil, Details: nil, InnerError: nil, AdditionalInfo: nil},
          Step: "Deploy",
      }
      Deploy: Code="" Message=""
  not to have occurred

  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/util/scenarios/updates/scaleupdown.go:32
------------------------------
Scale Out/In E2E tests [Fake] [Real] [Update] 
  should create a 2-replica sample deployment
  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/suites/scaleupdown/spec.go:37

• [SLOW TEST:14.321 seconds]
Scale Out/In E2E tests [Fake] [Real] [Update]
/home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/suites/scaleupdown/spec.go:26
  should create a 2-replica sample deployment
  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/suites/scaleupdown/spec.go:37
------------------------------
Scale Out/In E2E tests [Fake] [Real] [Update] 
  should get the deployment's pods and check that they are spread across nodes
  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/suites/scaleupdown/spec.go:41
•
------------------------------
Scale Out/In E2E tests [Fake] [Real] [Update] 
  should scale in the compute scale set to 1 vm
  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/suites/scaleupdown/spec.go:45
STEP: Parsing the external manifest
STEP: Updating the size of the compute scale set to 1 in the manifest
STEP: Calling update on the rp with the updated manifest
time="2018-11-22T13:53:16+01:00" level=info msg="convert to internal" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:53:16+01:00" level=info msg=enrich location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:53:16+01:00" level=info msg="read old config" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:53:16+01:00" level=info msg="merge old and new config" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:53:16+01:00" level=info msg="merging internal data models" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:53:16+01:00" level=info msg="validating internal data models" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:53:16+01:00" level=info msg="generating configs" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:53:16+01:00" level=info msg="persist config" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:53:16+01:00" level=info msg="generating arm templates" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:53:16+01:00" level=info msg="write helpers" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:53:16+01:00" level=info msg="starting update" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:53:16+01:00" level=info msg="draining compute-00000K" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:53:20+01:00" level=info msg="deleting compute-00000K" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:55:21+01:00" level=info msg="applying arm template deployment" location=westeurope resourceGroup=charlesakalugwu-test
time="2018-11-22T13:55:28+01:00" level=info msg="waiting for arm template deployment to complete" location=westeurope resourceGroup=charlesakalugwu-test

• Failure [165.476 seconds]
Scale Out/In E2E tests [Fake] [Real] [Update]
/home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/suites/scaleupdown/spec.go:26
  should scale in the compute scale set to 1 vm [It]
  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/suites/scaleupdown/spec.go:45

  Expected error:
      <*api.PluginError | 0xc420587220>: {
          Err: {Code: "", Message: "", Target: nil, Details: nil, InnerError: nil, AdditionalInfo: nil},
          Step: "Deploy",
      }
      Deploy: Code="" Message=""
  not to have occurred

  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/util/scenarios/updates/scaleupdown.go:32
------------------------------
Scale Out/In E2E tests [Fake] [Real] [Update] 
  should get the deployment's pods and check that they are back on a single node
  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/suites/scaleupdown/spec.go:49
•
------------------------------
Scale Out/In E2E tests [Fake] [Real] [Update] 
  should delete the sample deployment
  /home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/suites/scaleupdown/spec.go:53
•

Summarizing 2 Failures:

[Fail] Scale Out/In E2E tests [Fake] [Real] [Update] [It] should scale out the compute scale set to 2 vms 
/home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/util/scenarios/updates/scaleupdown.go:32

[Fail] Scale Out/In E2E tests [Fake] [Real] [Update] [It] should scale in the compute scale set to 1 vm 
/home/charles/Documents/go/src/github.com/openshift/openshift-azure/test/util/scenarios/updates/scaleupdown.go:32

Ran 6 of 6 Specs in 218.469 seconds
FAIL! -- 4 Passed | 2 Failed | 0 Pending | 0 Skipped
--- FAIL: TestE2eRealRP (218.47s)
FAIL
FAIL	github.com/openshift/openshift-azure/test/suites/scaleupdown	218.486s
```

**Comment by jim-minter** [comment]
@charlesakalugwu I am not seeing this using upgrade.sh on latest master (and the hack at #744).  Please can you dig into what you're seeing some more?  Also I am concerned about the nested error `Err: {Code: "", Message: "", Target: nil, Details: nil, InnerError: nil, AdditionalInfo: nil},` - that also should not be happening.

**Pull request closed without merging**
