### PR TITLE
Revert "Add default router profile to real rp sample manifest"

### PR DESCRIPTION
**Pull request by gburges**
This reverts commit 42a894b120140fcea4e10af8d4e2287676277e93.

```release-note
NONE
```

### CODE REVIEW

**Comment by gburges** [comment]
closes https://github.com/openshift/openshift-azure/issues/1624

**Comment by charlesakalugwu** [comment]
I think this was not ok afterall...we'll need to revert again 
https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-e2e-prod-vnet/61/build-log.txt

**Pull request merged**
