### PR TITLE
adding EndUser and ScaleUpDown to EveryPR

### PR DESCRIPTION
**Pull request by Makdaam**
- EndUser (+ approx 5min)
- ScaleUpDown - on same version (+ approx 13min), replaces https://github.com/openshift/release/pull/3575 in a way that avoids a new cluster spinup

```release-note
NONE
```

### CODE REVIEW

**Comment by Makdaam** [comment]
/retest
upgrade-v3.2 timeout
e2e not run (issues with CI were happening at the same time)

**Comment by Makdaam** [comment]
/test e2e
since /retest doesn't rerun "Expected" jobs.

**Comment by droslean** [comment]
> e2e not run (issues with CI were happening at the same time)

There is no problem with CI. It seems like a Github issue. The job `e2e` doesn't exist in GH API.
I sent email to GH support team.

**Comment by Makdaam** [comment]
Closing due to e2e stuck in "Expected — Waiting for status to be reported " state. Will open as a new PR soon.

**Pull request closed without merging**
