### PR TITLE
misc further tidying, mostly fakerp

### PR DESCRIPTION
**Pull request by jim-minter**
```release-note
NONE
```

### CODE REVIEW

**Comment by asalkeld** [comment]
@jim-minter looks like a real bug 

```
Panic: runtime error: invalid memory address or nil pointer dereference
goroutine 40 [running]:
runtime/debug.Stack(0x48, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi/middleware.Recoverer.func1.1(0xc0004f2e00, 0x1cc0a00, 0xc000310d20)
	/home/prow/go/src/github.com/openshift/openshift-azure/vendor/github.com/go-chi/chi/middleware/recoverer.go:28 +0x1b6
panic(0x18a92c0, 0x2fc0d60)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/openshift/openshift-azure/pkg/fakerp.(*Server).handlePut(0xc0002d22d0, 0x1cc0a00, 0xc000310d20, 0xc0004f2f00)
	/home/prow/go/src/github.com/openshift/openshift-azure/pkg/fakerp/customer_handlers.go:97 +0x2e7
github.com/openshift/openshift-azure/pkg/fakerp.(*Server).handlePut-fm(0x1cc0a00, 0xc000310d20, 0xc0004f2f00)
	/home/prow/go/src/github.com/openshift/openshift-azure/pkg/fakerp/routes.go:19 +0x48
```

**Comment by jim-minter** [comment]
yes thanks, I had fixed it but the commit accidentally got dropped - repushed

**Comment by mjudeikis** [comment]
after this I think our fakeRP is getting into some kind of shape :D

**Comment by mjudeikis** [comment]
/retest
flake: https://github.com/openshift/openshift-azure/issues/1597

**Comment by mjudeikis** [comment]
/retest
flake reopened: https://github.com/openshift/openshift-azure/issues/1400

**Pull request merged**
