### PR TITLE
move helpers persistence before creation

### PR DESCRIPTION
**Pull request by mjudeikis**
Moves config writer before creation.
fixes: https://github.com/openshift/openshift-azure/issues/1308

```release-note
NONE
```

### CODE REVIEW

**Comment by mjudeikis** [comment]
Do we care if we write all files again or we want to split CS just to separate function same as `writeHelpers`

**Comment by jim-minter** [comment]
don't mind either way - the real rp would write to the db indicating creating, then again indicating created - the fake rp db is the filesystem, so probably best to write twice

**Pull request merged**
