### PR TITLE
hash stability tests

### PR DESCRIPTION
**Pull request by jim-minter**
```release-note
NONE
```

this adds testing to make sure our hashes don't change over time, causing cluster rotations

### CODE REVIEW

**Comment by mjudeikis** [comment]
smart one... I like it
/lgtm

**Comment by jim-minter** [comment]
rebase fix, relgtming

**Comment by mjudeikis** [comment]
rebased, re-lgtm

**Comment by mjudeikis** [comment]
https://github.com/openshift/openshift-azure/issues/1363
/retest

**Comment by jim-minter** [comment]
thanks for the rebase!

**Pull request merged**
