### PR TITLE
update pluginconfig to use new image publisher

### PR DESCRIPTION
**Pull request by jim-minter**
```release-note
MSFT: image is now published from azureopenshift publisher, not redhat publisher
```

### CODE REVIEW

**Comment by jim-minter** [comment]
merge https://github.com/openshift/release/pull/6140 after this

**Comment by ehashman** [comment]
vmimage_test.go unit tests failing, and the upgrade jobs all appear to be actually failing when we attempt to change the images from the old publisher to the new one.

**Comment by jim-minter** [comment]
abandoning this for now :-(

**Pull request closed without merging**
