### PR TITLE
package names added by goimports

### PR DESCRIPTION
**Pull request by Makdaam**
Result of 
goimports -e -w -local=github.com/openshift/openshift-azure pkg cmd test
required for make verify to go through.

### CODE REVIEW

**Comment by Makdaam** [comment]
Please ignore for now, trying to find out what's wrong with my goimports settings.

**Comment by mjudeikis** [comment]
/hold
Just in case :) this is not needed as per current content

**Comment by Makdaam** [comment]
Resolved the issue with my goimports.
Checked out commit 04b5d21 of goimports to match @mjudeikis's version, and rebuilt it.

**Comment by mjudeikis** [comment]
Do we know if this is "new feature" or "bug"?

**Comment by Makdaam** [comment]
@mjudeikis There's a long discussion here https://github.com/golang/go/issues/28428 and it seems like it went in as a feature of new goimports.

**Comment by kargakis** [comment]
The very next moment we rebuild our test base image, we are going to hit this issue in CI. We should probably pin goimports in the test-base image into that commit for now.

**Comment by kargakis** [comment]
https://github.com/openshift/release/blob/87bee64d8fb540296a0d7b479e58065cfb88b38c/projects/azure/base-images/test-base.yaml#L64

**Comment by mjudeikis** [comment]
> The very next moment we rebuild our test base image, we are going to hit this issue in CI. We should probably pin goimports in the test-base image into that commit for now.

Good call! @Makdaam can you do this?

**Comment by Makdaam** [comment]
I'll take it.

**Pull request closed without merging**
