### PR TITLE
adding permissions to the customer-admin-cluster and cusomer-admin-project roles

### PR DESCRIPTION
**Pull request by Makdaam**
```release-note
Customer admin role gains the following permissions
- creating and managing daemonsets in customer created projects
- listing and deleting existing OAuth client authorizations
- SAR and RAR checks for user permission verification
- listing and viewing nodes, events, pods, cluster networks, netnamespaces for more low level insight
- listing SCCs
- listing available images and image tags
- listing all builds and build configs in a cluster
```

/hold
pending meeting to approve

### CODE REVIEW

**Comment by Makdaam** [comment]
/retest
flake #1780

**Comment by charlesakalugwu** [comment]
e2e-create flake #1643 #1438

**Pull request merged**
