### PR TITLE
Vendor openshift api

### PR DESCRIPTION
**Pull request by kargakis**
Of course we will also need openshift/api and not just client-go

/cc @mjudeikis @jim-minter

### CODE REVIEW

**Comment by kargakis** [comment]
Seems we don't vendor the kube api types. Need to fix that in a follow-up.

**Comment by kargakis** [comment]
> Seems we don't vendor the kube api types. Need to fix that in a follow-up.

Correction: we do vendor k8s.io/api but we werent pinning it in glide.yaml. Fixed here.

**Comment by jim-minter** [comment]
Bot went to sleep? Merging.

**Pull request merged**
