### PR TITLE
Old version cleanup

### PR DESCRIPTION
**Pull request by ehashman**
```release-note
NONE
```

None of the following plugin versions are currently deployed in production:

- v7.0 (upgrades completed to 7.1)
- v9.0 (upgrades completed)
- v10.0 (never deployed to RP)
- v10.2 (never deployed to RP)
- v11.0 (never deployed to RP)
- v12.0 (never deployed to RP)
- v12.1 (never deployed to RP)

### CODE REVIEW

**Comment by ehashman** [comment]
9.0 upgrade failure is expected since I removed support for that in this PR -- see https://github.com/openshift/release/pull/6268 for retiring the CI context. We don't have any prod clusters left running 9.0.

**Comment by ehashman** [comment]
flake #2126 
/test e2e-create-20191027-private

**Comment by ehashman** [comment]
/test e2e-create-20191027-private

infra node never came live

**Comment by ehashman** [comment]
flake #2126 
/test e2e-create-20191027-private

**Comment by Makdaam** [comment]
/retest
Flake #2126

**Comment by ehashman** [comment]
/retest
#2126 again :(

upgrade-9.0 now retired, no longer blocking.

**Pull request merged**
