### PR TITLE
Fixing the pluginversion with v10.2

### PR DESCRIPTION
**Pull request by kwoodson**
```release-note
NONE
```

### CODE REVIEW

**Comment by thekad** [comment]
Don't you have to create a whole new stanza for 10.2 ?

**Comment by jim-minter** [comment]
@kad I accidentally merged all that already

**Comment by jim-minter** [comment]
I am expecting this to fail tests until @asalkeld has built the images involved

**Comment by kwoodson** [comment]
I had to get the latest changes pulled down and rebase on top of them.

**Comment by asalkeld** [comment]
image pushed to acr

**Comment by asalkeld** [comment]
@jim-minter ptal (other required commits cherry-picked) I have rebuilt and pushed the new image to acr

**Pull request merged**
