### PR TITLE
Consistent e2e CustomDimensions with unit tests based off prow info.

### PR DESCRIPTION
**Pull request by pnasrat**
Enables prow specific appinsights for consistent querying in appinsights.

```release-note
NONE
```

### CODE REVIEW

**Comment by pnasrat** [comment]
Following query demonstrates working on this pull request:

```
customMetrics
| where customDimensions.prowprnumber == 2186
| where customDimensions.type == "ginkgo"
| limit 100 
```

First result I get is for [Top Level] Reimage VM E2E tests [ReimageVM][LongRunning] should be possible for an SRE to reimage a VM in a scale set

Custom Dimensions now populated:

```json
{"resourcegroup":"ci-2186-e2e-upgrade-kshtvo","prowjobbuild":"415","prowprnumber":"2186","prowjobname":"pull-ci-azure-master-upgrade-v10.1.1","prowjobtype":"presubmit","type":"ginkgo"}
```
</details>

**Comment by olga-mir** [comment]
/hold

upgrade v71 needs to be removed from this PR (it has been removed from `release`) need to find a way to drop it from existing PRs
`verify` fails for all PRs with `Potential DoS vulnerability via decompression bomb`

**Comment by pnasrat** [comment]
rebasing

**Comment by pnasrat** [comment]
As I am no longer on the team I'm closing my PRs. People can pull from my branches and take forward if they want

**Pull request closed without merging**
