### PR TITLE
Remove/modify code referring to v13 [WIP]

### PR DESCRIPTION
**Pull request by nilsanderselde**
```release-note
Since version 13 was skipped, remove it from repo.

Mostly file deletions, with a few line removals. Besides that, there is a single check which has been incremented from 13 to 14.
```

### CODE REVIEW

**Comment by mjudeikis** [comment]
/hold 
remove hold when release repo removals merges

**Comment by nilsanderselde** [comment]
/unhold

https://github.com/openshift/release/pull/6715 has been merged

**Pull request merged**
