### PR TITLE
MDSD + azsec-clamav

### PR DESCRIPTION
**Pull request by thekad**
```release-note
Sending clamav scan events to geneva
```
This uses the new image built with azsec-clamav and clamav
Also removing the kickstart blocks now that v7 got pushed with kickstart.repo enabled cc @charlesakalugwu ptal

### CODE REVIEW

**Comment by thekad** [comment]
/hold
this needs the new image published which @ehashman already triggered

**Comment by ehashman** [comment]
@thekad image is published and ready for this PR

**Comment by thekad** [comment]
Looking into failures, the docs say the instruction should succeed but that seems to not be the case, digging.

**Comment by thekad** [comment]
Flakes #1903 and #1438 

/retest

**Comment by thekad** [comment]
/hold cancel
cc @openshift/sig-azure

**Pull request merged**
