### PR TITLE
Avoid setting VMScaleSetVMReimageInput during master VM reimaging

### LINKED ISSUE #1068: Master vm update process fails after update of azure-sdk-for-go
The reimage process for master VMs now fails after the updates to `azure-sdk-for-go` pushed forward in #1064 and #1065 

The error is reproducible by trying to run any of the update-based e2e tests such as keyrotation and looks as follows:

```
500 Internal Error: Failed to rotate cluster secrets: UpdateMasterAgentPoolReimage: compute.VirtualMachineScaleSetVMsClient#Reimage: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The value of parameter tempDisk is invalid." Target="tempDisk" 
```

Sample CI run: https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1067/pull-ci-openshift-openshift-azure-master-e2e-azure-keyrotation/60/

Introduced in commit: https://github.com/openshift/openshift-azure/pull/1064/commits/6c07dc605ebab81d1c7df7a3fdb4d3640cd0d420

/kind bug
/cc @jim-minter @asalkeld @mjudeikis

### PR DESCRIPTION
**Pull request by charlesakalugwu**
closes #1068

/cc @jim-minter @kargakis @asalkeld @mjudeikis

### CODE REVIEW

**Comment by kargakis** [comment]
Can you also try bumping scalesets to `2018-10-01` as an alternative and see whether we can wipe tmp disks in that version w/o a problem?

**Comment by charlesakalugwu** [comment]
@kargakis the problem persists even after bumping compute to `2018-10-01`

**Comment by jim-minter** [comment]
/lgtm

thanks @charlesakalugwu and @kargakis

**Pull request merged**
