### PR TITLE
use -X to store sync commit

### PR DESCRIPTION
**Pull request by jim-minter**
@kargakis @kwoodson I was hoping to do it this way so the commit goes straight into the logging

### CODE REVIEW

**Comment by mjudeikis** [comment]
need to rollback this too as it will break ci
https://github.com/openshift/release/pull/1475

**Comment by kargakis** [comment]
https://github.com/openshift/release/pull/1506

/lgtm

**Comment by mjudeikis** [comment]
@kargakis @jim-minter please merge this as CI now fails :)  small enough to deal with fallout post

**Comment by kargakis** [comment]
Let's wait for the e2e test to finish? It should pass for this PR.

**Comment by mjudeikis** [comment]
and it failed with the flake...

**Comment by kargakis** [comment]
The image build was successful and `sync` seems to run in the cluster and all the infra resources are created so this is probably safe to green-button merge.

**Pull request merged**
