### PR TITLE
Don't compress when calculating the hash

### PR DESCRIPTION
**Pull request by asalkeld**
relates to #1127

### CODE REVIEW

**Comment by thekad** [comment]
this LGTM but will wait for @kwoodson to weigh in

**Comment by kwoodson** [comment]
Running a test locally and will report back.

**Comment by kwoodson** [comment]
@asalkeld I was able to reproduce the issue with this PR.  The hash when running `make e2e-scaleupdown` causes a full rotation of masters.

**Comment by jim-minter** [comment]
isn't gzip deterministic?  not convinced we should go this route?

**Comment by jim-minter** [comment]
/hold
for more discussion in #1127

**Comment by jim-minter** [comment]
closing this, we're rolling back to the config blob

**Pull request closed without merging**
