### PR TITLE
Move teardown script from openshift/release

### PR DESCRIPTION
**Pull request by kargakis**
Moving the teardown script from openshift/release in openshift-azure. Eventually this script should be removed in favor of requesting the cluster cleanup via createorupdate -rm, just need to add artifacts gathering to it.

/cc mjudeikis kwoodson

### CODE REVIEW

**Comment by mjudeikis** [comment]
lgtm 
wait for others

**Comment by kargakis** [comment]
openshift/release PR is https://github.com/openshift/release/pull/2114

**Comment by kargakis** [comment]
@mjudeikis seems the api server and etcd pod names have been updated in 3.11, ptal

**Comment by kargakis** [comment]
Actually this is probably not worth it - I have opened a PR to gather artifacts (https://github.com/openshift/openshift-azure/pull/721)

**Comment by kargakis** [comment]
Instead of this I am planning on writting an all-in-one script that:
* sets up the aad object
* creates dns zone and cname
* runs createorupdate with -rm, -artifact-dir, -artifact-kubeconfig, and -exec, and optionally -update and -update-exec
* deletes the dns zone

**Comment by kargakis** [comment]
Then we can collapse all containers and all templates (apart from the base and node builds) into one.

**Comment by mjudeikis** [comment]
/test e2e
looks like network flake on azure side

**Comment by mjudeikis** [comment]
@kargakis https://github.com/openshift/openshift-azure/issues/723

**Pull request closed without merging**
