### PR TITLE
remove out-of-date configurable, causes an error in the logs

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by charlesakalugwu** [comment]
@jim-minter would be great if you could leave some short summary about the error in the logs

**Comment by jim-minter** [comment]
@charlesakalugwu on master api server / controller startup:
```
Feb 12 19:52:39 master-000000 dockerd-current[5817]: E0212 19:52:38.348181       1 helpers.go:134] Encountered config error json: unknown field "masterCount" in object *config.MasterConfig, raw JSON:
Feb 12 19:52:39 master-000000 dockerd-current[5817]: {"admissionConfig":{"pluginConfig":{"BuildDefaults":{"configuration":{"apiVersion":"v1","env":[],"kind":"BuildDefaultsConfig","resources":{"limits":{},"requests":{}}}},"BuildOverrides":{"configuration":{"apiVersion":"v1","kind":"BuildOverridesConfig"}},"openshift.io/ImagePolicy":{"configuration":{"apiVersion":"v1","executionRules":[{"matchImageAnnotations":[{"key":"images.openshift.io/deny-execution","value":"true"}],"name":"execution-denied","onResources":[{"resource":"pods"},{"resource":"builds"}],"reject":true,"skipOnResolutionFailure":true}],"kind":"ImagePolicyConfig"}}}},"aggregatorConfig":{"proxyClientInfo":{"certFile":"aggregator-front-proxy.crt","keyFile":"aggregator-front-proxy.key"}},"apiLevels":["v1"],"apiVersion":"v1","auditConfig":{"enabled":true},"authConfig":{"requestHeader":{"clientCA":"front-proxy-ca.crt","clientCommonNames":["aggregator-front-proxy"],"extraHeaderPrefixes":["X-Remote-Extra-"],"groupHeaders":["X-Remote-Group"],"usernameHeaders":["X-Remote-User"]}},"controllerConfig":{"election":{"lockName":"openshift-master-controllers"},"serviceServingCert":{"signer":{"certFile":"service-signer.crt","keyFile":"service-signer.key"}}},"controllers":"*","corsAllowedOrigins":null,"dnsConfig":{"bindAddress":"0.0.0.0:8053","bindNetwork":"tcp4"},"etcdClientInfo":{"ca":"master.etcd-ca.crt","certFile":"master.etcd-client.crt","keyFile":"master.etcd-client.key","urls":["https://master-000000:2379"]},"etcdStorageConfig":{"kubernetesStoragePrefix":"kubernetes.io","kubernetesStorageVersion":"v1","openShiftStoragePrefix":"openshift.io","openShiftStorageVersion":"v1"},"imageConfig":{"format":"registry.access.redhat.com/openshift3/ose-${component}:${version}"},"imagePolicyConfig":{"internalRegistryHostname":"docker-registry.default.svc:5000"},"kind":"MasterConfig","kubeletClientInfo":{"ca":"ca.crt","certFile":"master.kubelet-client.crt","keyFile":"master.kubelet-client.key","port":10250},"kubernetesMasterConfig":{"apiServerArguments":{"cloud-config":["/etc/origin/cloudprovider/azure.conf"],"cloud-provider":["azure"],"storage-backend":["etcd3"],"storage-media-type":["application/vnd.kubernetes.protobuf"]},"controllerArguments":{"cloud-config":["/etc/origin/cloudprovider/azure.conf"],"cloud-provider":["azure"],"cluster-signing-cert-file":["/etc/origin/master/ca.crt"],"cluster-signing-key-file":["/etc/origin/master/ca.key"]},"masterCount":3,"masterIP":"127.0.0.1","proxyClientInfo":{"certFile":"master.proxy-client.crt","keyFile":"master.proxy-client.key"},"schedulerConfigFile":"/etc/origin/master/scheduler.json","servicesNodePortRange":"","servicesSubnet":"172.30.0.0/16","staticNodeNames":[]},"masterClients":{"externalKubernetesClientConnectionOverrides":{"acceptContentTypes":"application/vnd.kubernetes.protobuf,application/json","burst":400,"contentType":"application/vnd.kubernetes.protobuf","qps":200},"externalKubernetesKubeConfig":"","openshiftLoopbackClientConnectionOverrides":{"acceptContentTypes":"application/vnd.kubernetes.protobuf,application/json","burst":600,"contentType":"application/vnd.kubernetes.protobuf","qps":300},"openshiftLoopbackKubeConfig":"openshift-master.kubeconfig"},"masterPublicURL":"https://jminterosa2.eastus.cloudapp.azure.com","networkConfig":{"clusterNetworks":[{"cidr":"10.128.0.0/14","hostSubnetLength":9}],"externalIPNetworkCIDRs":["0.0.0.0/0"],"networkPluginName":"redhat/openshift-ovs-networkpolicy","serviceNetworkCIDR":"172.30.0.0/16"},"oauthConfig":{"assetPublicURL":"https://jminterosa2.eastus.cloudapp.azure.com/console/","grantConfig":{"method":"auto"},"identityProviders":[{"login":true,"mappingMethod":"claim","name":"Azure AD","provider":{"apiVersion":"v1","claims":{"email":["email"],"id":["sub"],"name":["name"],"preferredUsername":["unique_name"]},"clientID":"4287674d-0c2d-4ab0-ab78-054f66fae89d","clientSecret":"7a0560eb-8d79-42e7-abe4-6a52a019f699","kind":"OpenIDIdentityProvider","urls":{"authorize":"https://login.microsoftonline.com/7a1815fb-63ba-4af7-8f33-e7333e421980/oauth2/authorize","token":"https://login.microsoftonline.com/7a1815fb-63ba-4af7-8f33-e7333e421980/oauth2/token"}}}],"masterCA":"ca.crt","masterPublicURL":"https://jminterosa2.eastus.cloudapp.azure.com","masterURL":"https://jminterosa2.eastus.cloudapp.azure.com","sessionConfig":{"sessionMaxAgeSeconds":3600,"sessionName":"ssn","sessionSecretsFile":"/etc/origin/master/session-secrets.yaml"},"tokenConfig":{"accessTokenMaxAgeSeconds":86400,"authorizeTokenMaxAgeSeconds":500}},"projectConfig":{"defaultNodeSelector":"node-role.kubernetes.io/compute=true","securityAllocator":{"mcsAllocatorRange":"s0:/2","mcsLabelsPerProject":5,"uidAllocatorRange":"1000000000-1999999999/10000"}},"routingConfig":{"subdomain":"a29c60c5y8s03voyk8oi.osadev.cloud"},"serviceAccountConfig":{"managedNames":["default","builder","deployer"],"masterCA":"ca.crt","privateKeyFile":"serviceaccounts.private.key","publicKeyFiles":["serviceaccounts.public.key"]},"servingInfo":{"bindAddress":"0.0.0.0:443","bindNetwork":"tcp4","certFile":"master.server.crt","clientCA":"ca.crt","keyFile":"master.server.key","maxRequestsInFlight":500,"namedCertificates":[{"certFile":"/etc/origin/master/named/console.crt","keyFile":"/etc/origin/master/named/console.key","names":["jminterosa2.eastus.cloudapp.azure.com"]}],"requestTimeoutSeconds":3600},"volumeConfig":{"dynamicProvisioningEnabled":true}}
```

**Comment by asalkeld** [comment]
looks great, just trying to get the tests to pass

**Pull request merged**
