### PR TITLE
Product manifest for our VM Images

### PR DESCRIPTION
**Pull request by Makdaam**
```release-note
NONE
```
Code which generates a list of packages installed in every VM image generated for ARO.

WIP, waiting for prodsec response if this is enough.

### CODE REVIEW

**Comment by Makdaam** [comment]
Needs rebasing - in progress.

**Comment by jim-minter** [comment]
@Makdaam what's the status on this?

**Comment by jim-minter** [comment]
@Makdaam no reply? ;-)

**Comment by Makdaam** [comment]
Sorry for the late reply.
It's in progress. I want to make sure the script provides all the required information to the ProdSec team before I commit/push and cancel hold.

**Comment by Makdaam** [comment]
Rebased, updated the script.
These are the only 2 artifacts we need to generate the software manifest.
In parallel I'm updating the release engineering SOP on how to generate a manifest from those 2 files.

**Comment by kwoodson** [comment]
@Makdaam  What's the status of this?  Have you heard back from the prodsec team?

**Comment by Makdaam** [comment]
I'll have to chase this PR to get merged. The code is ready and we should produce artifacts for every release that goes to prod.
In the mean time
/retest

**Pull request merged**
