### PR TITLE
Update vendor deps.

### PR DESCRIPTION
**Pull request by y-cote**
This adds the github.com/openshift/service-catalog.git repo to vendor/.
Upcoming OSBA e2e tests need ClusterServiceBroker definitions.

Signed-off-by: Yannick Cote <ycote@redhat.com>

```release-note
NONE
```

### CODE REVIEW

**Comment by jim-minter** [comment]
/retest
flake #1343 
@y-cote can this be merged or is it really still wip?

**Comment by y-cote** [comment]
> /retest
> flake #1343
> @y-cote can this be merged or is it really still wip?

good to go. thanks

**Comment by charlesakalugwu** [comment]
#1442

**Comment by charlesakalugwu** [comment]
#1362

**Comment by charlesakalugwu** [comment]
#1410

**Comment by jim-minter** [comment]
#1362 again, going to hard merge

**Pull request merged**
