### PR TITLE
Fix generated code check in make verify

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/openshift/openshift-azure/issues/690

/cc asalkeld

### CODE REVIEW

**Comment by kargakis** [comment]
Our test base image picked up the latest go-bindata code, hence the new generated diff

https://github.com/go-bindata/go-bindata/pull/2

@openshift/sig-azure, fyi, update your go-bindata with `go get -u github.com/go-bindata/go-bindata/...`

**Comment by asalkeld** [comment]
I am not sure this patch does anything (it seems the same before and after).
```
git grep --name-only 'Code generated by .* DO NOT EDIT.*' -- ':^vendor' ':^hack'
pkg/addons/bindata.go
pkg/arm/bindata.go
pkg/jsonpath/parser.go
pkg/util/mocks/mock_arm/arm.go
pkg/util/mocks/mock_azureclient/azureclient.go
pkg/util/mocks/mock_azureclient/mock_storage/storage.go
pkg/util/mocks/mock_cluster/types.go
pkg/util/mocks/mock_wait/wait.go
[angus] ~/.../openshift/openshift-azure  (fix-verify)$ git grep --name-only 'Code generated by .* DO NOT EDIT.*' -- 'pkg/*'
pkg/addons/bindata.go
pkg/arm/bindata.go
pkg/jsonpath/parser.go
pkg/util/mocks/mock_arm/arm.go
pkg/util/mocks/mock_azureclient/azureclient.go
pkg/util/mocks/mock_azureclient/mock_storage/storage.go
pkg/util/mocks/mock_cluster/types.go
pkg/util/mocks/mock_wait/wait.go
```
Also it seems to be picking up the new header fine:
-// Code generated by go-bindata. DO NOT EDIT. @generated
+// Code generated by go-bindata. (@generated) DO NOT EDIT.

**Comment by kargakis** [comment]
It's the same, the latter works for CI. The generated code was picked up
because we rebuilt our test base image recently and the latest version of
go-bindata was picked up.

**Pull request merged**
