### PR TITLE
bye bye logbridge

### PR DESCRIPTION
**Pull request by mjudeikis**
Remove logbridge in favor of Geneva.

### CODE REVIEW

**Comment by jim-minter** [comment]
all looks fine so far

**Comment by mjudeikis** [comment]
/hold cancel
@jim-minter @kargakis if can merge this I will start putting other PR in place

**Comment by jim-minter** [comment]
removing [wip] tag, still need to fix tests though ;)

**Comment by mjudeikis** [comment]
https://github.com/openshift/release/pull/2140 needs to be merged

**Comment by mjudeikis** [comment]
@kargakis @charlesakalugwu please lgtm again

**Pull request merged**
