### PR TITLE
upgrade the azure sdk.

### PR DESCRIPTION
**Pull request by andyliuliming**

### CODE REVIEW

**Comment by sozercan** [comment]
looks like this is for aligning with aks-engine v0.29.1 release that'll vendored into the RP
https://github.com/Azure/aks-engine/blob/master/Gopkg.lock#L30

**Comment by kargakis** [comment]
We should be able to get rid of our mocked clients after this PR gets merged

https://github.com/openshift/openshift-azure/issues/725

**Comment by jim-minter** [comment]
@andyliuliming many thanks for this PR!
I'm closing in favour of #1064, which builds on your work: adds a missing import to get this through test + passing the new argument to Reimage through our client layer into the main codebase.

**Pull request closed without merging**
