### PR TITLE
fixing issues causing updates on every run of sync pod

### PR DESCRIPTION
**Pull request by Makdaam**
```release-note
NONE
```
Fixing issues with canary app apparent "diff" (type mismatch + no explicit api version).
AMQ is waiting for https://github.com/openshift/library/pull/171 to merge (Travis issues)
Todo: redhat-sso-cd-openshift

Replaces #1575

### CODE REVIEW

**Comment by Makdaam** [comment]
https://github.com/openshift/library/pull/172
for recurring redhat-sso-cd updates.

**Comment by thekad** [comment]
/hold
cancel hold once the referenced PR is merged

**Comment by Makdaam** [comment]
I think there's no point in waiting for the library merge. This PR fixes one of the issues detected by sync pod test. 
Referencing the openshift/library PR was unnecessary here.
Should have pointed to #1543 

/hold cancel

**Pull request merged**
