### PR TITLE
Fix group sync for UserPrincipalName match

### PR DESCRIPTION
**Pull request by Makdaam**
adding a different case for when Mail field is set but UserPrincipalName matches a cluster user

```release-note
Fix user syncing when Mail field is set, but UserPrincipalName matches the cluster username
```

### CODE REVIEW

**Comment by jim-minter** [comment]
@Makdaam please ping me for review when rebased

**Comment by Makdaam** [comment]
/retest
Flake #1775 
+ couldn't reach github

**Comment by Makdaam** [comment]
/hold cancel
rebased, 
@jim-minter please take a look

**Comment by Makdaam** [comment]
/retest
flake #2135

**Comment by jim-minter** [comment]
/lgtm
/hold

@mjudeikis please review and hold cancel if happy

**Comment by ehashman** [comment]
/retest
flake #2136

**Pull request merged**
