### PR TITLE
Admin API bug fixes and createorupdate enhancements

### PR DESCRIPTION
**Pull request by kargakis**
A grab bag of admin API enhancements and bug fixes:
* make createorupdate send admin requests even for cluster creation (even though it is disallowed by admin validation, it will be useful for QE testing)
* add masterPoolProfile in the admin api (oversight)
* ignore sending the provisioning state in admin requests by createorupdate
* retry admin requests by createorupdate
* fix merging the config struct for admin requests
* unit tests for the admin merging code

### CODE REVIEW

**Comment by kargakis** [comment]
Figured out we are not setting MasterPoolProfile in the admin api. Fixed plus added unit testing.

**Comment by kargakis** [comment]
/hold

planning on writting a couple of more unit tests

**Comment by kargakis** [comment]
Unit tests added, this is ready for a review

**Comment by mjudeikis** [comment]
overall looks good. quite big, but good

**Comment by kargakis** [comment]
https://github.com/openshift/openshift-azure/issues/850

/retest

**Comment by mjudeikis** [comment]
lgtm from my side
@charlesakalugwu @jim-minter ?

**Comment by asalkeld** [comment]
lgtm

**Comment by kargakis** [comment]
https://github.com/openshift/openshift-azure/issues/814#issuecomment-448952671

/retest

**Pull request merged**
