### PR TITLE
Simple move of validate into the api package

### LINKED ISSUE #383: collapse some packages
Not sure how others feel about it but I think we should collapse `pkg/checks` in `pkg/healthcheck` and `pkg/validate` in `pkg/api`. Thoughts?

@openshift/sig-azure

### PR DESCRIPTION
**Pull request by asalkeld**
closes #383

### CODE REVIEW

**Comment by kargakis** [comment]
Needs a rebase

**Comment by asalkeld** [comment]
the error is: cmd/sync/sync.go:131:13: undefined: acsapi

**Comment by asalkeld** [comment]
The automatic merge caused a problem, I had to rebase. it re-added a "acsapi" instead of the new "api" import.

**Pull request merged**
