### PR TITLE
Cache storage client keys in sync

### PR DESCRIPTION
**Pull request by kargakis**
This PR updates the sync process to cache the storage client to avoid listing keys more than once to avoid getting ratelimited since the storage RP limits seem to be lower than other RP limits.

Closes https://github.com/openshift/openshift-azure/issues/606

### CODE REVIEW

**Comment by kargakis** [comment]
Discussed with Jim, we agreed that we don't know whether we need to cache or not the config blob so just caching the keys for now should be enough.

**Comment by mjudeikis** [comment]
lgtm, will wait for @asalkeld input

**Pull request merged**
