### PR TITLE
Fixes make verify

### PR DESCRIPTION
**Pull request by m1kola**
`validate-generated.sh` doesn't fail because we do not run generate before diffing files.

Reverts a line that was accidentally removed in #1850

```release-note
NONE
```

### CODE REVIEW

**Comment by m1kola** [comment]
This run is expected to fail on `make verify`, because the branch contains old v8 bindata files.

Needs to be merged after #1855 

/hold

**Comment by m1kola** [comment]
@ehashman CC'ing you as we were discussing this issue in slack. Note https://github.com/openshift/openshift-azure/pull/1856#issuecomment-521302458

/cc @ehashman

**Comment by ehashman** [comment]
@m1kola I think I'd rather see CI fail and then get fixed together in the same PR, once verify fails here can you add the commit that regenerates the bindata?

**Comment by m1kola** [comment]
Ok, it failed [here](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1856/verify/790).

I updated the PR with new bindata.

**Comment by ehashman** [comment]
flake #552

**Pull request merged**
