### PR TITLE
Revert "Merge pull request #2204 from mjudeikis/node.count"

### PR DESCRIPTION
**Pull request by mjudeikis**
This reverts commit bf0695ef9f5b4dd59d442b405da01f6613bc3731, reversing
changes made to f5fade170b01c0c649aaf490eb7ce541a2a7cb3d.

```release-note
NONE
```

### CODE REVIEW

**Comment by asalkeld** [comment]
@mjudeikis what's wrong with increasing the node count? Why are we reverting?

**Comment by mjudeikis** [comment]
There is snat exhaustslion issue on lt. Check old Pris pr. It needs more
testing and chsnges

**Pull request merged**
