### PR TITLE
E2E test for working binary builds 

### PR DESCRIPTION
**Pull request by pnasrat**
Create a basic e2e test for binary builds

https://docs.openshift.com/container-platform/3.11/dev_guide/dev_tutorials/binary_builds.html

```release-note
NONE
```

### CODE REVIEW

**Comment by pnasrat** [comment]
Please hold off review as still WIP

**Comment by pnasrat** [comment]
I'd like to get initial code review/feedback for my testing strategy here.  The actual fix as discussed is a config change (removing the DenyEscalatingExec plugin) which I'll rebase ontop of v15 when done.

**Comment by pnasrat** [comment]
Run on dev cluster with change:

```
Openshift on Azure end user e2e tests [EndUser][Builds][EveryPR]
/home/pnasrat/workspace/src/github.com/openshift/openshift-azure/test/e2e/specs/builds.go:22
  should be able to create builds [EndUser][Builds]
  /home/pnasrat/workspace/src/github.com/openshift/openshift-azure/test/e2e/specs/builds.go:24
------------------------------
S
Ran 1 of 40 Specs in 16.123 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 39 Skipped
--- PASS: TestE2E (16.13s)
PASS
ok  	github.com/openshift/openshift-azure/test/e2e	18.865s
```

**Comment by pnasrat** [comment]
So my test passing so this can at least start review for early feedback on my test approach if possible.

<details>

```
• [SLOW TEST:209.108 seconds]
Openshift on Azure end user e2e tests [CustomerAdmin][EveryPR]
/home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/osba_app.go:83
  should create and validate an OpenShift Broker App [CustomerAdmin][OSBA]
  /home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/osba_app.go:84
------------------------------
Openshift on Azure end user e2e tests [EndUser][Builds][EveryPR] 
  should be able to create builds [EndUser][Builds]
  /home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/builds.go:24
STEP: creating a binary BuildConfig
STEP: validating starting a build for a binary BuildConfig
STEP: validating build completed for a binary BuildConfig
STEP: deleting project

• [SLOW TEST:19.384 seconds]
Openshift on Azure end user e2e tests [EndUser][Builds][EveryPR]
/home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/builds.go:22
  should be able to create builds [EndUser][Builds]
  /home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/builds.go:24
```

</details>

**Comment by pnasrat** [comment]
OK one of the failures is likely related:

<details>

```
• Failure [10.778 seconds]
Openshift on Azure customer-admin e2e tests [CustomerAdmin][EveryPR]
/home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/customer_admin.go:27
  should not be able to create a non-whitelisted privileged container [It]
  /home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/customer_admin.go:355

  Unexpected error:
      <*errors.StatusError | 0xc000dd46c0>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {SelfLink: "", ResourceVersion: "", Continue: ""},
              Status: "Failure",
              Message: "pods \"test\" is forbidden: unable to validate against any pod security policy: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]",
              Reason: "Forbidden",
              Details: {Name: "test", Group: "", Kind: "pods", UID: "", Causes: nil, RetryAfterSeconds: 0},
              Code: 403,
          },
      }
```

</details>

**Comment by pnasrat** [comment]
So it looks like there may be a flake in https://github.com/openshift/openshift-azure/blob/b70e97b4988f04e720e0277034b6559faebd37b5/test/e2e/specs/customer_admin.go#L393 where we can either fail validating the err.ErrStatus.Message

```
"admission webhook \"aro-admission-controller.aro.openshift.io\" denied the request: spec.containers[0]: Forbidden: requires privileges but image is not whitelisted on platform"
```
Some times it passes, but I also see the SCC causing the rejection in some test runs

```
pods "test" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
```

**Comment by pnasrat** [comment]
Latest failures were timeouts ... 

/retest

**Comment by pnasrat** [comment]
Timeout 

/retest

**Comment by kwoodson** [comment]
@pnasrat If this is ready to be reviewed, Will you please remove [WIP] from title and let's get it reviewed!

Thanks

**Comment by pnasrat** [comment]
@kwoodson PTAL

**Pull request merged**
