### PR TITLE
Update location headers set in fakerp delete handler

### LINKED ISSUE #1028: Update location headers returned from deletes in fake rp
We need to update the Location headers we return from deletes in the fakerp so we can stop serving at /.

/kind feature

@kargakis

### PR DESCRIPTION
**Pull request by charlesakalugwu**
closes #1028 

/cc @kargakis @mjudeikis

### CODE REVIEW

**Comment by kargakis** [comment]
/lgtm
/hold

let's merge this once we resolve the routing issue

**Comment by kargakis** [comment]
Tested locally, works like a charm
```
$ ./hack/delete.sh 
+ [[ 0 -eq 0 ]]
+ [[ ! -e _data/containerservice.yaml ]]
+ [[ 0 -eq 1 ]]
++ awk '/^    resourceGroup:/ { print $2 }'
+ export RESOURCEGROUP=mkargakiosa
+ RESOURCEGROUP=mkargakiosa
+ [[ -n '' ]]
+ go generate ./...
bindata.go
bindata.go
+ trap 'return_id=$?; set +ex; kill $(lsof -t -i :8080); wait $(lsof -t -i :8080); exit $return_id' EXIT
+ go run cmd/createorupdate/createorupdate.go -request=DELETE
+ go run cmd/fakerp/main.go
INFO[2019-01-14T14:00:27+01:00] deleting cluster                             
INFO[2019-01-14T14:00:29+01:00] starting the fake resource provider          
INFO[2019-01-14T14:00:29+01:00] starting server on localhost:8080            
INFO[2019-01-14T14:00:29+01:00] deleting cluster                             
DEBU[2019-01-14T14:00:29+01:00] 127.0.0.1:44552 DELETE /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/mkargakiosa/providers/Microsoft.ContainerService/openShiftManagedClusters/mkargakiosa?api-version=2018-09-30-preview 
INFO[2019-01-14T14:00:36+01:00] deleting resource group mkargakiosa          
INFO[2019-01-14T14:00:37+01:00] waiting for cluster deletion                 
DEBU[2019-01-14T14:00:37+01:00] 127.0.0.1:44552 GET /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/mkargakiosa/providers/Microsoft.ContainerService/openShiftManagedClusters/mkargakiosa 
DEBU[2019-01-14T14:01:37+01:00] 127.0.0.1:44552 GET /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/mkargakiosa/providers/Microsoft.ContainerService/openShiftManagedClusters/mkargakiosa 
DEBU[2019-01-14T14:02:37+01:00] 127.0.0.1:44552 GET /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/mkargakiosa/providers/Microsoft.ContainerService/openShiftManagedClusters/mkargakiosa 
DEBU[2019-01-14T14:03:37+01:00] 127.0.0.1:44552 GET /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/mkargakiosa/providers/Microsoft.ContainerService/openShiftManagedClusters/mkargakiosa 
DEBU[2019-01-14T14:04:37+01:00] 127.0.0.1:44552 GET /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/mkargakiosa/providers/Microsoft.ContainerService/openShiftManagedClusters/mkargakiosa 
INFO[2019-01-14T14:05:22+01:00] deleted resource group mkargakiosa           
DEBU[2019-01-14T14:05:37+01:00] 127.0.0.1:44552 GET /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/mkargakiosa/providers/Microsoft.ContainerService/openShiftManagedClusters/mkargakiosa 
INFO[2019-01-14T14:05:37+01:00] deleted cluster                              
+ return_id=0
+ set +ex
signal: terminated
```

**Comment by charlesakalugwu** [comment]
#958

**Pull request merged**
