### PR TITLE
fix stale generated code

### PR DESCRIPTION
**Pull request by jim-minter**
@kargakis is master currently broken?  we don't retest as we merge code?

### CODE REVIEW

**Comment by kargakis** [comment]
You need to update your local gomock repo, I've sent an email in aos-azure

**Comment by jim-minter** [comment]
yes, but I think our repo is actually broken since #813 merged

**Comment by kargakis** [comment]
ouch, I thought those tests were fresh. my bad.

**Comment by jim-minter** [comment]
@kargakis is there a relatively painless way of having the CI prevent this from happening again?

**Pull request merged**
