### PR TITLE
Improve the docker pull retries in the startup script

### PR DESCRIPTION
**Pull request by asalkeld**
When quay.io is unavailable the user has to wait for the full cluster timeout
before knowing that it has failed as the pull will retry for ever.

Now it will retry every minute 5 times.

We now also log the reties.

```release-note
NONE
```

### CODE REVIEW

**Comment by ehashman** [comment]
Please rebase against v8

**Comment by asalkeld** [comment]
> Does it matter if the background `docker pull` of node image fails?
> 
> ```shell
> docker pull {{ .Config.Images.Node }} &>/dev/null &
> ```

I don't know why that is there... it is used in "systemctl enable atomic-openshift-node.service". That should fail if it can't get the image. at a guess, this is to just make startup faster, so we probably don't want to block on that.

**Comment by m1kola** [comment]
Thanks for the explanation @asalkeld 

Changes look good to me, but there is a conflict in bindata

**Comment by ehashman** [comment]
LGTM but needs rebase.

**Pull request merged**
