### PR TITLE
fix and extend e-mail matching in customer-admin-controller

### PR DESCRIPTION
**Pull request by kwoodson**
```release-note
Fix and extend e-mail matching in customer-admin-controller
```

### CODE REVIEW

**Comment by kwoodson** [comment]
Failed because of capacity in our subscription:
```
time="2019-11-14T16:55:30Z" level=warning msg="deployment failed: &azure.ServiceError{Code:\"DeploymentFailed\", Message:\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\", Target:(*string)(nil), Details:[]map[string]interface {}{map[string]interface {}{\"code\":\"Conflict\", \"message\":\"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"OperationNotAllowed\\\",\\r\\n    
\\\"message\\\": \\\"The operation couldn't be completed as it results in exceeding quota limit of standardDSv3Family Cores. Maximum allowed: 300, Current in use: 300, Additional requested: 2. Read more about quota limits at https://aka.ms/AzurePerVMQuotaLimits. Submit a request for Quota increase using the link https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%22225e02bc-43d0-43d1-a01a-17e584a4ef69%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D.\\\"\\r\\n  }\\r\\n}\"}}, InnerError:map[string]interface {}(nil), AdditionalInfo:[]map[string]interface {}(nil)}" func="pkg/fakerp.GetDeployer.func1()" file="pkg/fakerp/fakerp.go:118"
```

**Comment by jim-minter** [comment]
@asalkeld this must land in 10.2.

**Comment by jim-minter** [comment]
merged to #2082

**Pull request closed without merging**
