### PR TITLE
Updating image for v12.2

### PR DESCRIPTION
**Pull request by kwoodson**
```release-note
Updating image and openshift version to 3.11.154
```

### CODE REVIEW

**Comment by jim-minter** [comment]
lgtm - waiting for image to publish

**Comment by kwoodson** [comment]
I think this was a flake
```
Expected
      <[]*standard.TestError | len:1, cap:1>: [
          {
              Bucket: "createStatefulApp",
              Err: {
                  s: "templateinstance e2e-test-asptv/e2e-test-asptv failed: Failed (readiness failed on DeploymentConfig e2e-test-asptv/django-psql-persistent)",
              },
          },
      ]
  to be empty
```

**Pull request merged**
