### PR TITLE
Update VM image and containers to OpenShift 3.11.157

### PR DESCRIPTION
**Pull request by ehashman**
```release-note
Update to OpenShift [3.11.157](https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-3-11-157)
```

/hold

Waiting on image publication.

### CODE REVIEW

**Comment by ehashman** [comment]
/retest
/hold cancel

Looks like the image is live now.

**Comment by ehashman** [comment]
flake #1481 I think
/retest

**Comment by pnasrat** [comment]
I'll review once e2e-create-20191027-private passes

**Comment by pnasrat** [comment]
Also I'm very confused as peeking at the latest log file [e2e-create-20191027-private](https://prow.svc.ci.openshift.org/log?id=276&job=pull-ci-azure-master-e2e-create-20191027-private) prow says it is still running but the tail of the log looks complete to me (and didn't get the failure as above):

```
Ran 28 of 39 Specs in 2782.841 seconds
SUCCESS! -- 28 Passed | 0 Failed | 0 Pending | 11 Skipped
--- PASS: TestE2E (2782.85s)
PASS
ok  	github.com/openshift/openshift-azure/test/e2e	2791.311
```

**Comment by pnasrat** [comment]
Though the prow log didn't change from when I looked previous at a run of 2791s (around 46 mins) versus the  2h4m19s time for success in prow.

**Pull request merged**
