### PR TITLE
Allow test manifest to run for prod clusters

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by kargakis** [comment]
It's not going to work yet

**Comment by asalkeld** [comment]
we are getting heaps of

```
  Expected error:
      <*errors.errorString | 0xc000082b30>: {
          s: "http: no Location header in response",
      }
      http: no Location header in response
  not to have occurred
```

**Comment by kargakis** [comment]
Will try to figure out what's the issue with Location in a follow-up PR.

**Pull request merged**
