### PR TITLE
Change the order the monitoring stack is healthchecked

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/openshift/openshift-azure/issues/850

/cc @charlesakalugwu @jim-minter

### CODE REVIEW

**Comment by charlesakalugwu** [comment]
https://github.com/openshift/openshift-azure/issues/904

**Comment by kargakis** [comment]
> #904

The issue in this PR seems to be different
```
 time="2018-12-13T13:56:51Z" level=debug msg="400 Bad Request: Failed to apply request: WaitForNodes: Get https://e2e-clbwahbh.westeurope.cloudapp.azure.com/api/v1/nodes/master-000000: net/http: TLS handshake timeout"```

**Comment by kargakis** [comment]
https://github.com/openshift/openshift-azure/issues/905

/retest

**Comment by kargakis** [comment]
@mjudeikis fyi

**Pull request merged**
