### PR TITLE
Make kubeconfigs derived

### PR DESCRIPTION
**Pull request by jim-minter**
Avoids storing kubeconfigs in the cluster Config struct - they can be derived from the contents of the Config struct.

### CODE REVIEW

**Comment by jim-minter** [comment]
also for consideration for private preview @mjudeikis @kargakis @pweil-

**Comment by mjudeikis** [comment]
I see where you going with this, but this means now that each tool we want use kubeconfig needs to generate it. This is not a big blocker, but SRE's or MSFT now will need to generate one too when acceesing the cluster. I think this might be little bit inconveniant for PP.

**Comment by mjudeikis** [comment]
+ MSFT was asking for cluster-reader kubeconfig for their side of monitoring/automation. If we merge this, they will need to generate one too.

**Comment by jim-minter** [comment]
The reason I'm interested in doing this now is for config API cleanup.  We can straightforwardly make the kubeconfig generation part of a "libosa" which is reusable by anyone who has access to the Config struct.  It's not hard to generate a kubeconfig - for example create.sh still places the admin.kubeconfig in _data.

**Comment by pweil-** [comment]
Is this a bug that needs merged on day of freeze?  Are we going to be in a spot where we can't change this next week?  Doesn't feel like something that needs last minute attention.

**Comment by kargakis** [comment]
reopen if still relevant

**Pull request closed without merging**
