### PR TITLE
Remove RealRP tests

### PR DESCRIPTION
**Pull request by gburges**
```release-note
NONE
```

### CODE REVIEW

**Comment by gburges** [comment]
/hold

Waiting on talking with MSFT about testing

**Comment by charlesakalugwu** [comment]
upgrade-v5.2 flake #661 
/retest

**Comment by gburges** [comment]
connected to https://github.com/openshift/release/pull/4444

**Comment by asalkeld** [comment]
can you please add the jira reference, i do remember seeing something about this in jira, but helps if there is a link/number to prevent us from searching for it

**Comment by gburges** [comment]
@asalkeld Jira ticket https://jira.coreos.com/browse/AZURE-343

**Comment by mgahagan73** [comment]
This looks good to me, I found a few ARO test cases in QE that will need to be updated to remove [FAKE] when run in the future but I can updated them.

/lgtm

**Comment by ehashman** [comment]
I'd like to go ahead and merge this as it significantly reduces complexity from our tests, and we are not really using the results from the RealRP tests at present.

/hold cancel

**Comment by ehashman** [comment]
/retest
flake - master-000002 didn't come up?

**Pull request merged**
