### PR TITLE
always create StorageClasses before objects that use them

### PR DESCRIPTION
**Pull request by jim-minter**
@kargakis @kwoodson @mjudeikis @pweil- I'm fairly confident this will help our PV timeout problem.  I'm pretty sure that part/all of it is a race between the statefulset controller creating PVCs and the default StorageClass having been created (note, alphabetically speaking StorageClass is just after StatefulSet).

### CODE REVIEW

**Comment by jim-minter** [comment]
might fix #361

**Comment by kargakis** [comment]
I've thought about this too but it feels to me like a kube bug. Mind opening an issue upstream?

/lgtm

**Comment by jim-minter** [comment]
change was fixing typo in commit, readding label

**Comment by jim-minter** [comment]
for reference, https://github.com/kubernetes/kubernetes/issues/44370 is basically the issue upstream

**Comment by mjudeikis** [comment]
/lgtm
the only concert is how fast each controller registers their components. So we would not have same condition as with crd

**Comment by jim-minter** [comment]
there's no controller/status associated with the storageclass and it is expected that the create call does not return before a read call would be able to access it.

**Pull request merged**
