### PR TITLE
Fixing scap by removing audispd failures

### PR DESCRIPTION
**Pull request by kwoodson**
Fixing latest scap failures by removing audispd remote sender failures.

```release-note:
None
```

### CODE REVIEW

**Comment by kwoodson** [comment]
@ehashman @m1kola @mjudeikis PTAL

**Comment by mjudeikis** [comment]
So this failure removed the test from scap? How did you find out which one is failing?

**Comment by kwoodson** [comment]
I would like to see #1836 fail before we add the fix.

/hold

**Comment by kwoodson** [comment]
@mjudeikis 
> So this failure removed the test from scap? How did you find out which one is failing?

I ran the vmimage-validate and grabbed the scap-report.html.  Saw that we had 2 items failing.  I'm not sure how the popped up as they've always been there.  I disabled them and added them to our tracking spreadsheet.

**Comment by m1kola** [comment]
> I would like to see #1836 fail before we add the fix.

@kwoodson here is [`vmimage` run](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1836/pull-ci-azure-master-vmimage/37) from that PR

**Comment by ehashman** [comment]
#1836 is failing as desired: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1836/pull-ci-azure-master-vmimage/37/artifacts/scap-report.html

/hold cancel

**Pull request merged**
