### PR TITLE
logging consolidation

### PR DESCRIPTION
**Pull request by jim-minter**
This PR fixes an issue whereby checksum labels weren't being added correctly to daemonsets, etc.
It then fixes the azure logging configuration to pick up all relevant pods, and simplifies the configuration.

### CODE REVIEW

**Comment by jim-minter** [comment]
@mjudeikis ptal

**Comment by mjudeikis** [comment]
lgtm,

What is the reason for GroupKind vs Kind?

**Comment by kargakis** [comment]
needs a rebase

**Comment by jim-minter** [comment]
rebased

**Pull request merged**
