### PR TITLE
parameterize some of the arm template

### PR DESCRIPTION
**Pull request by pweil-**
@amanohar - takes a stab at adding parameters for some of the fields you mentioned in #156

### CODE REVIEW

**Comment by mjudeikis** [comment]
Not the biggest fan of this as now we will have `{{- if eq $.Config.ImageResourceName "" }}` and parameters all around the place. Preference would be to stick to single method for injecting data?

**Comment by pweil-** [comment]
Closing this based on scrum discussions.  We can reopen if necessary

**Pull request closed without merging**
