### PR TITLE
Prepare for northeurope

### PR DESCRIPTION
**Pull request by jim-minter**
```release-note
NONE
```

@mjudeikis once this merges should be able to set REGION=eastus,westeurope,northeurope in the CI secret.  We have quota on northeurope and the VMSS fix is rolled out there - ptal.

### CODE REVIEW

**Comment by jim-minter** [comment]
@asalkeld fyi too

**Comment by mjudeikis** [comment]
PR name sounds like my future plan in one sentence!
+ name is a little bit irrelevant as there is more changes than stated :/
/lgtm

**Comment by mjudeikis** [comment]
release changes are not applied:
```
Using metricsbridge image registry.svc.ci.openshift.org/ci-op-d59xrfgm/stable:metricsbridge
Using tlsproxy image ${TLSPROXY_IMAGE}
Using canary image ${CANARY_IMAGE}
```

**Comment by mjudeikis** [comment]
https://github.com/openshift/release/pull/3334

**Comment by jim-minter** [comment]
flakes #1409 and #1410

**Comment by jim-minter** [comment]
```
+ go run cmd/createorupdate/createorupdate.go -admin-manifest=test/manifests/fakerp/admin-update.yaml
time="2019-04-03T02:52:17Z" level=info msg="using region eastus"
time="2019-04-03T02:52:17Z" level=info msg="ensuring resource group e2e-upgrade-jim-minter-1397-kdeksn"
time="2019-04-03T02:52:18Z" level=fatal msg="resources.GroupsClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code=\"InvalidResourceGroupLocation\" Message=\"Invalid resource group location 'eastus'. The Resource group already exists in location 'westeurope'.\""
exit status 1
+ return_id=1
+ set +ex
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
time="2019-04-03T02:52:20Z" level=info msg="starting the fake resource provider" func=main.main file="/go/src/github.com/openshift/openshift-azure/cmd/fakerp/main.go:20"
time="2019-04-03T02:52:20Z" level=info msg="starting server on localhost:8080" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).Run" file="/go/src/github.com/openshift/openshift-azure/pkg/fakerp/server.go:77"
++ cleanup
++ set +e
++ [[ -n /tmp/artifacts ]]
++ exec
make: *** wait: No child processes.  Stop.
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.
```

**Comment by jim-minter** [comment]
based on previous review, merging

**Pull request merged**
