### PR TITLE
make admin kubeconfig available on master nodes

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
@kwoodson ptal

**Comment by kwoodson** [comment]
@jim-minter, What is the difference of the admin.kubeconfig in this PR vs /root/.kube/config?
```
[root@master-000000 ~]# oc get pods --loglevel=8
I0831 17:12:30.253906   21678 loader.go:357] Config loaded from file /root/.kube/config
```

**Comment by kwoodson** [comment]
@jim-minter, Found it.  The start script in master does the following:
```
mkdir -p /root/.kube
cp /etc/origin/master/openshift-master.kubeconfig /root/.kube/config
```

**Comment by jim-minter** [comment]
yes - it shouldn't.

please lgtm if happy

**Comment by kwoodson** [comment]
sorry, thought I had.

/lgtm

**Pull request merged**
