### PR TITLE
Move vm image building to rhel 7.7

### PR DESCRIPTION
**Pull request by kwoodson**
Moving the vmimage build officially 7.7.  Underneath the covers we are already using the latest image (7.7).

From the `/etc/redhat-release`:
```
[cloud-user@master-000000 ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.7 (Maipo)
```

The latest 7.7 image has been published:
```
  {
    "offer": "RHEL",
    "publisher": "RedHat",
    "sku": "7-RAW",
    "urn": "RedHat:RHEL:7-RAW:7.7.2019090418",
    "version": "7.7.2019090418"
  },
```

Packages installed at first boot in the latest vm image [build](https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-vmimage/140/build-log.txt)
```
  Verifying  : libcgroup-0.41-21.el7.x86_64                             123/123 
```

Packages in a previous build:
```
  Verifying  : 12:dhclient-4.2.5-68.el7_5.1.x86_64                      475/475 
```

```release-note:
Moving VM Image to 7.7
```

### CODE REVIEW

**Comment by kwoodson** [comment]
Local `make vmimage`:
```
  "tags": {
    "gitcommit": "v4.0-802-g79303e4a0-dirty",
    "kernel": "3.10.0-1062.1.1.el7.x86_64",
    "openshift": "3.11.141-1.git.0.be05365.el7.x86_64",
    "valid": "true"
  },
  "type": "Microsoft.Compute/images"
}
Built image rhel7-3.11-201909041743
```

**Comment by thekad** [comment]
Do you want to get #1905 done first? does it matter at all?
/test vmimage

**Comment by kwoodson** [comment]
Flake:
```
$ git fetch https://github.com/openshift/openshift-azure.git pull/1925/head
fatal: unable to access 'https://github.com/openshift/openshift-azure.git/': Could not resolve host: github.com
# Error: exit status 128
```

**Comment by kwoodson** [comment]
yet another flake.  Created https://github.com/openshift/openshift-azure/issues/1932
```
time="2019-09-10T15:23:30Z" level=fatal msg="cannot update aad app secret: graphrbac.ApplicationsClient#Patch: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"Unknown\" Message=\"Unknown service error\" Details=[{\"odata.error\":{\"code\":\"Directory_ResourceSizeExceeded\",\"date\":\"2019-09-10T15:23:30\",\"message\":{\"lang\":\"en\",\"value\":\"The size of the object has exceeded its limit. Please reduce the number of values and retry your request.\"},\"requestId\":\"3484ebe7-c4ea-4a0f-a17d-07f920659062\"}}]"
```

**Pull request merged**
