### PR TITLE
release v4.0

### PR DESCRIPTION
**Pull request by jim-minter**
```release-note
NONE
```

### CODE REVIEW

**Comment by jim-minter** [comment]
@mjudeikis not sure why prow included ci/prow/internal-upgrade-v4.0 or ci/prow/upgrade-v4.0 here :-/

**Comment by jim-minter** [comment]
scaleupdown stuck because of https://github.com/openshift/release/pull/3326
merging

**Comment by mjudeikis** [comment]
we getting closer to eliminate templates but not yet there.

**Pull request merged**
