### PR TITLE
Cleanup OSA RP client code

### PR DESCRIPTION
**Pull request by kargakis**
Removing the extra functionality since we are going to test e2e upgrades via the e2e framework.

### CODE REVIEW

**Comment by kwoodson** [comment]
I like this removal.  I'll defer to others for their opinion.

**Comment by kargakis** [comment]
https://github.com/openshift/openshift-azure/issues/814

/retest

**Comment by kargakis** [comment]
https://github.com/openshift/openshift-azure/issues/804

/retest

**Pull request merged**
