### PR TITLE
fix image building rbac error

### LINKED ISSUE #1545: vmimage build broken
VM Image build broken in periodic and ad-hock:
image

I suspect RBAC problems (details below) 

https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-node-image/30/build-log.txt -> https://github.com/openshift/openshift-azure/issues/1442
https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-node-image/28/build-log.txt -> 
https://github.com/openshift/openshift-azure/issues/1442

https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-node-image/26/build-log.txt -> https://github.com/openshift/openshift-azure/issues/1448

https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-node-image/27/build-log.txt -> This issue
https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-node-image/29/build-log.txt - > This issue 

Details on the issue. Builds are failing with the error:
```
I0418 07:46:37.236640       1 azure_vmss.go:651] VirtualMachineScaleSetsClient.CreateOrUpdate for service (e2e-test-ignsz/ilb): scale set (ss-compute-1555572073) - updating, err=compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client '394c9ed6-7cbc-49a9-b9d8-648326c66ef4' with object id '394c9ed6-7cbc-49a9-b9d8-648326c66ef4' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/rhel7-311-201904180653-e2e/providers/Microsoft.Compute/virtualMachineScaleSets/ss-compute-1555572073'; however, it does not have permission to perform action 'read' on the linked scope(s) '/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/images/providers/Microsoft.Compute/images/rhel7-3.11-201904180653'."
```

Where customRole specifies required details:
```
    "assignableScopes": [
      "/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69"
    ],
    "description": null,
    "id": "/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/providers/Microsoft.Authorization/roleDefinitions/9bc35064-26cf-4536-8e65-40bd22a41071",
    "name": "9bc35064-26cf-4536-8e65-40bd22a41071",
    "permissions": [
      {
        "actions": [
          "Microsoft.Compute/disks/read",
          "Microsoft.Compute/disks/write",
          "Microsoft.Compute/disks/delete",
          *******"Microsoft.Compute/images/read",********
          "Microsoft.Compute/virtualMachineScaleSets/read",
          "Microsoft.Compute/virtualMachineScaleSets/write",
          "Microsoft.Compute/virtualMachineScaleSets/manualUpgrade/action",
          "Microsoft.Compute/virtualMachineScaleSets/virtualMachines/read",
          "Microsoft.Compute/virtualMachineScaleSets/virtualMachines/write",
          "Microsoft.Compute/virtualMachineScaleSets/virtualMachines/networkInterfaces/read",
          "Microsoft.KeyVault/vaults/read",
          "Microsoft.Network/loadBalancers/read",
          "Microsoft.Network/loadBalancers/write",
          "Microsoft.Network/loadBalancers/delete",
          "Microsoft.Network/loadBalancers/backendAddressPools/join/action",
          "Microsoft.Network/networkSecurityGroups/read",
          "Microsoft.Network/networkSecurityGroups/write",
          "Microsoft.Network/publicIPAddresses/read",
          "Microsoft.Network/publicIPAddresses/write",
          "Microsoft.Network/publicIPAddresses/delete",
          "Microsoft.Network/publicIPAddresses/join/action",
          "Microsoft.Network/virtualNetworks/subnets/read",
          "Microsoft.Network/virtualNetworks/subnets/join/action",
          "Microsoft.Storage/storageAccounts/read",
          "Microsoft.Storage/storageAccounts/listKeys/action"
        ],
        "dataActions": [],
        "notActions": [],
        "notDataActions": []
      }
    ],
```

Original issue log: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1538/pull-ci-openshift-openshift-azure-master-vmimage/5/build-log.txt

Based on Azure docs, we should be able to use it via `assignableScopes` https://docs.microsoft.com/en-us/azure/role-based-access-control/role-definitions#assignablescopes

Might be that something changed in the Azure RBAC model and we were not notified. As the same RBAC model was working before. 

Running test locally to verify.

### PR DESCRIPTION
**Pull request by jim-minter**
```release-note
NONE
```

fixes #1545 
@mjudeikis fyi

### CODE REVIEW

**Comment by asalkeld** [comment]
make unit works for me, not sure why it won't build in ci, trying again.
/retest

**Comment by asalkeld** [comment]
```
go test ./... -coverprofile=coverage.out -covermode=atomic
# github.com/openshift/openshift-azure/cmd/azure.test
2019/04/23 00:13:30 $WORK/b365/_pkg_.a(_go_.o): error reading read $WORK/b365/_pkg_.a: cannot allocate memory
FAIL	github.com/openshift/openshift-azure/cmd/azure [build failed]
```

**Comment by mjudeikis** [comment]
``` 
"400 Bad Request: Failed to apply request: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"BadRequestFormat\" Message=\"The request was incorrectly formatted.\"" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest" file="/home/prow/go/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:11"
```

**Comment by jim-minter** [comment]
redis timeout extended in https://github.com/openshift/openshift-azure/pull/1556

**Pull request merged**
