### PR TITLE
make default storage class use xfs filesystem

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by kargakis** [comment]
@mjudeikis any idea why we still see this error?
```
time="2018-11-13T12:39:43Z" level=debug msg="400 Bad Request: Failed to apply request: invalid properties.openShiftVersion \"v3.10\"" resourceGroup=ci-op-d0j8tx7x-8474e
```

**Comment by mjudeikis** [comment]
@kargakis seen this one then CI operator caches images in the namespace. did rerun complete? 
https://github.com/openshift/release/issues/2055

**Pull request merged**
