### PR TITLE
WIP: Config deep-copying

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by jim-minter** [comment]
WIP, the difficult pieces here are around deep copying keys/certs etc

**Comment by jim-minter** [comment]
worth looking at trying to get rid of `testOpenShiftClusterYAML` in our tests with this PR as well

**Comment by mjudeikis** [comment]
@jim-minter gave a shot to update this, but I think its worth waiting until https://github.com/openshift/openshift-azure/pull/254 goes in to do this

**Comment by kargakis** [comment]
@jim-minter @pweil- this is getting very very ugly (x509.Certificate contains `interface{}` values :/). I was suggested in IRC to switch our certificates to be stored as raw `[]byte` types in Config. That would ease deep-copying them. Thoughts?

**Comment by jim-minter** [comment]
@kargakis I agree this is not looking like the right direction.  It's a little unsavoury, but for now, why not just implement a Config DeepCopy function which serialises the input to json and unserialises to a new object?  We're not going to be doing it that much, it gets us over the hurdle, and there really are much worse alternatives.

**Comment by jim-minter** [comment]
@kargakis see https://github.com/openshift/openshift-azure/pull/315 for an alternative approach

**Comment by kargakis** [comment]
I like it better

/close

**Pull request closed without merging**
