### PR TITLE
Remove outdated SCAP benchmarks, disable false negatives

### LINKED ISSUE #2269: SCAP checks failing after upstream changes
I think we just need to update the benchmarks to avoid these warnings: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-ci-azure-vmimage-validate-osa311-latest/200#1:build-log.txt%3A269

### PR DESCRIPTION
**Pull request by ehashman**
```release-note
NONE
```

Addresses (but does not fix) #2269.

### CODE REVIEW

**Comment by ehashman** [comment]
flake

/retest

**Comment by ehashman** [comment]
Changes here:

- Remove the SCAP benchmarks that were coming up as warnings in the logs, e.g. https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-ci-azure-vmimage-validate-osa311-latest/200#1:build-log.txt%3A257
- Disabled the two SCAP benchmarks that are false failures while we wait for an upstream fix, see https://bugzilla.redhat.com/show_bug.cgi?id=1823576#c3 for details

**Comment by kwoodson** [comment]
@ehashman 

What's the plan to manage these longer term?  Once these get fixed upstream, are we planning on adding these back?

Other than that it looks good to me.

**Comment by ehashman** [comment]
> What's the plan to manage these longer term? Once these get fixed upstream, are we planning on adding these back?

Yes, that's my plan. I'm subscribed to the upstream bugzilla so should know when the fixes become available.

**Pull request merged**
