### PR TITLE
send output from unit tests to app insights

### PR DESCRIPTION
**Pull request by Makdaam**
```release-note
NONE
```
A command line tool which sends unit test results and durations to app insights.

### CODE REVIEW

**Comment by charlesakalugwu** [comment]
@Makdaam what's the need for this work? We already have a codecov integration for pushing, analysing and taking actions on unit test results. Something for e2e tests metrics instead would really be beneficial.

**Comment by Makdaam** [comment]
@charlesakalugwu codecov gives us coverage info, but no pass/fail or performance data. This PR puts the pass/fail and timing data in the same format as the e2e insights.

**Comment by thekad** [comment]
> @charlesakalugwu codecov gives us coverage info, but no pass/fail or performance data. This PR puts the pass/fail and timing data in the same format as the e2e insights.

So I get that, I am just curious what the usefulness would be?

**Comment by Makdaam** [comment]
I wanted to put all the data regarding all tests in one place to include that in a test babysitter's dashboard. For unit tests the duration of passing tests would be the useful metric (fails would be caught by the PR author).

Then again after your question I'm wondering if durations measured in µs/ms per test are worth chasing.

**Comment by ehashman** [comment]
Seems reasonable to me, if we don't need this we can revert it.

/lgtm

**Pull request merged**
