### PR TITLE
Blob read unit tests

### PR DESCRIPTION
**Pull request by kargakis**
Apparently reading a malformed blob does not return an error. May need to use [encoding/json/#Decoder.DisallowUnknownFields](https://golang.org/pkg/encoding/json/#Decoder.DisallowUnknownFields) to catch those cases.

```release-note
NONE
```

### CODE REVIEW

**Comment by jim-minter** [comment]
@kargakis :wave: , how are you doing? :smile: 

thanks for the PR!

/lgtm

**Comment by kargakis** [comment]
> @kargakis 👋 , how are you doing? 😄

hi @jim-minter, I'm doing alright, how about you? I'm feeling very productive today it seems :)

**Pull request merged**
