### PR TITLE
relax the hash test for the version under development otherwise we'll go mad

### PR DESCRIPTION
**Pull request by jim-minter**
```release-note
NONE
```

### CODE REVIEW

**Comment by mjudeikis** [comment]
https://github.com/openshift/openshift-azure/pull/1434
/retest

**Comment by jim-minter** [comment]
I think you meant #1400 @mjudeikis? ;-)
Please can I have an lgtm?

**Comment by mjudeikis** [comment]
/lgtm 
Yes! too many tabs!

**Comment by thekad** [comment]
/lgtm
yes please

**Comment by jim-minter** [comment]
#1102

**Comment by jim-minter** [comment]
hard merging as prerequisite to get other flake fixes in

**Pull request merged**
