### PR TITLE
Pin master configs to local api-servers

### LINKED ISSUE #1632: Pin kubelets to local masters rather than the load balanced master FQDN
This will enable us to use private masters behind an internal load balancer, as Azure internal LBs can't do circular routing.

### PR DESCRIPTION
**Pull request by ehashman**
```release-note
NONE
```

Closes #1632. After making these changes and doing a local e2e test run, I couldn't find anything on the masters attempting to connect via the api-server FQDN anymore.

### CODE REVIEW

**Comment by ehashman** [comment]
/retest

flake #1410

**Comment by kwoodson** [comment]
This looks good.  I did not test the regex but looks correct.

**Comment by ehashman** [comment]
/retest

Prow flaked :(

/hold

Putting a hold on this for @jim-minter / @mjudeikis to take a look but will take off WIP as everything looks to be passing tests.

**Comment by ehashman** [comment]
```
 Ran 11 of 33 Specs in 698.396 seconds
SUCCESS! -- 11 Passed | 0 Failed | 0 Pending | 22 Skipped
--- PASS: TestE2E (698.40s)
PASS 
```

:woman_shrugging:  prow why

/retest

**Comment by jim-minter** [comment]
/lgtm

I think I'm convinced that it was as straightforward as this ... hooray!

**Pull request merged**
