### PR TITLE
Remove registry init container

### PR DESCRIPTION
**Pull request by kargakis**
Move storage account key discovery in the sync process.

Ref https://github.com/openshift/openshift-azure/issues/270

We may want to fix applying config in init containers even though we won't have any after this PR merges anyway but separate PR.

@openshift/sig-azure ptal

### CODE REVIEW

**Comment by kwoodson** [comment]
I like this approach since it is the approach I took in #170.

/lgtm

**Comment by kargakis** [comment]
https://github.com/openshift/openshift-azure/issues/267

/retest

**Comment by kargakis** [comment]
@stevekuznetsov @bbguimaraes @droslean seems that when I run retest, I get the same failed run in the report.

**Comment by kargakis** [comment]
The e2e pod is mysteriously gone. Only related event in the namespace
```
10m         10m          1         e2e-azure.154fad4928814f27    Pod       spec.containers{teardown}                    Normal    Killing          kubelet, origin-ci-ig-n-cj00   Killing container with id docker://teardown:Need to kill Pod
```
Unclear why it's deleted.

**Comment by kargakis** [comment]
bindata rebase, retagging

**Comment by stevekuznetsov** [comment]
You should see all the inputs reused in the /retest -- but not the test itself. Is that not the case?

**Comment by mjudeikis** [comment]
we have some serious flakes here... need to investigate on ci-operator jobs side :/

**Comment by kargakis** [comment]
> You should see all the inputs reused in the /retest -- but not the test itself. Is that not the case?

Yeah, I saw a couple of times that the failed test is reused.

**Comment by kargakis** [comment]
> Another strange thing, test that failed 2h ago and the namespace is already deleted from the cluster.

Correction: the test shows up as pending on Github, and in the logs it seems that it runs.

**Comment by kargakis** [comment]
The sync process fails with the following log:
```
time="2018-08-31T09:35:18Z" level=info msg="Error while syncing: cannot sync cluster config: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/ci-op-b2bhkln9-6cb1c/providers/Microsoft.Storage/storageAccounts/l8oleo6rdum5zslh0syia6hj/listKeys?api-version=2018-02-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Identity not found\"}"
```
Definitely caused by my PR. Trying to figure out why.

**Comment by kargakis** [comment]
Ah, looks like the sync pod is lacking the azure credentials in its env.

**Pull request merged**
