### PR TITLE
Validate AAD service principal authentication and role

### PR DESCRIPTION
**Pull request by jim-minter**
```release-note
Plugin now validates AAD service principal authentication and, if
customerAdminGroupID is set, that the Directory.Read.All permission is
granted.
```

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@jim-minter the automation in this repo wants to add the `sig/azure` label to everything, but the label has not yet been configured to exist. Could you please add it [here](https://github.com/openshift/release/blob/0929069937d7f42924fe5264d1c3d659d2715cbc/core-services/prow/02_config/_labels.yaml#L408-L413) to any repos you think it needs to be on?

**Comment by ehashman** [comment]
@jim-minter how do I validate this change? There are no new automated tests.

**Comment by ehashman** [comment]
@stevekuznetsov everything in this repo is sig/azure-related so adding the label here wouldn't be particularly useful... from what I can see in the linked config file, we only target that at openshift/release, which is intended (since it's a shared repo and lets us filter on our team's issues/PRs)?

**Comment by jim-minter** [comment]
@stevekuznetsov what is the connection between this PR and your request?

**Comment by ehashman** [comment]
```
 github.com/openshift/openshift-azure/pkg/plugin --- FAIL: TestHowUserConfigChangesCausesRotations (9.89s)
github.com/openshift/openshift-azure/pkg/plugin     --- FAIL: TestHowUserConfigChangesCausesRotations/no_changes (1.04s)
github.com/openshift/openshift-azure/pkg/plugin         integration_test.go:671: [invalid properties.authProfile.identityProviders["Azure AD"]: could not authenticate: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'e16dc530-2fe3-4a62-851f-fd479b0784ed' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.\r\nTrace ID: 69395b5f-9eb8-4c81-8248-2cbcf4c67300\r\nCorrelation ID: 4e904293-15fc-499b-af05-cbe4914e5926\r\nTimestamp: 2019-11-27 18:14:55Z","error_codes":[90002],"timestamp":"2019-11-27 18:14:55Z","trace_id":"69395b5f-9eb8-4c81-8248-2cbcf4c67300","correlation_id":"4e904293-15fc-499b-af05-cbe4914e5926","error_uri":"https://login.microsoftonline.com/error?code=90002"}]
github.com/openshift/openshift-azure/pkg/plugin         integration_test.go:671: [invalid properties.authProfile.identityProviders["Azure AD"]: could not authenticate: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'e16dc530-2fe3-4a62-851f-fd479b0784ed' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.\r\nTrace ID: 69395b5f-9eb8-4c81-8248-2cbcf4c67300\r\nCorrelation ID: 4e904293-15fc-499b-af05-cbe4914e5926\r\nTimestamp: 2019-11-27 18:14:55Z","error_codes":[90002],"timestamp":"2019-11-27 18:14:55Z","trace_id":"69395b5f-9eb8-4c81-8248-2cbcf4c67300","correlation_id":"4e904293-15fc-499b-af05-cbe4914e5926","error_uri":"https://login.microsoftonline.com/error?code=90002"}] 
```

I think we have a missing mock for the unit tests?

**Comment by stevekuznetsov** [comment]
If the label is not useful, then please remove it from your configuration [here](https://github.com/openshift/openshift-azure/blob/8c6e8392680369e6be8abf3b67ac5d86e48f0f77/OWNERS#L21-L22). The connection to _this_ PR is the same as to any. The OWNERS line I linked to instructs our robots to try to add the label to every PR in this repository.

**Comment by jim-minter** [comment]
> The connection to this PR is the same as to any.
@stevekuznetsov then this PR is not the place for the conversation, thanks.

**Comment by ehashman** [comment]
flake #1778 
/test e2e-create-20190430

**Pull request merged**
