### PR TITLE
add validate-imports.go

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by kargakis** [comment]
@jim-minter is the added benefit on top of our current use of goimports the dot imports handling?

**Comment by kargakis** [comment]
tcp timeout

/retest

**Comment by jim-minter** [comment]
dot imports, stricter group order (std library, dot imports, !local, local), can't have multiple separated groups of the same type.

**Comment by mjudeikis** [comment]
I'm still surprised how you just pull out code like this out of your magic hat...
/lgtm

**Pull request merged**
