### PR TITLE
Revert docker build strategy restriction

### PR DESCRIPTION
**Pull request by ehashman**
Reverts #1303.

Documented at https://docs.openshift.com/container-platform/3.11/admin_guidesecuring_builds.html#disabling-a-build-strategy-globally

```release-note
Add support for docker build strategy
```

### CODE REVIEW

**Comment by ehashman** [comment]
This seems to be passing tests now so removing the WIP. This is a hard revert of #1303, not sure if we want to modify the tests rather than remove them but removing them was easy so I just did that.

**Comment by asalkeld** [comment]
@ehashman looks good, happy to lgtm. Is everyone happy with the security concerns?

**Comment by charlesakalugwu** [comment]
@ehashman I think it would be nicer to modify the test to confirm that docker builds are permitted. Besides that, this lgtm. 
@asalkeld are you referring to @grantomation's finding that the ose-docker-build pod needs to run with the "privileged" scc? I have reservations about this and look forward to hear what others think.

**Comment by jim-minter** [comment]
/lgtm
this matches osd behaviour.
@ehashman @thekad please can you ensure our docs are in sync (will need to revert @thekad 's docs PR)

**Comment by ehashman** [comment]
Yup, I'll follow up with a reversion of that PR. It's the last thing remaining in the JIRA.

**Pull request merged**
