### PR TITLE
Add missing deps

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/openshift/openshift-azure/issues/396

@openshift/sig-azure

### CODE REVIEW

**Comment by mjudeikis** [comment]
`hpcloud` O_o was it not being vendored with `ginko` deps?

**Comment by mjudeikis** [comment]
ou, they dont vendor at all... :/ 
/lgtm

**Comment by kargakis** [comment]
Even if they don't vendor, we are pruning nested vendored directories anyway, right?

**Comment by mjudeikis** [comment]
am I missing something, where is glide.yaml update?

**Pull request merged**
