### PR TITLE
Store the workspace key in the secret

### LINKED ISSUE #1975: monitoring workspace key not in secret
https://github.com/openshift/openshift-azure/pull/1812/files#diff-30ed770edf86ff1b12ea9fcd03fe0635R325-R328 is incorrect: the key should be written into a secret and read in the daemonset using valueFrom / secretKeyRef.

Please fix as a priority.

cc @ehashman

### PR DESCRIPTION
**Pull request by asalkeld**
```release-note
MSFT: store the monitoring workspace key in the secrets not in the clusterConfig
```
closes #1975 
/cc @jim-minter @charlesakalugwu 

Note: @jim-minter you removed the monitoring section from the manifest, but that left us with no way
to test. I have put it back with a conditional block around it.

### CODE REVIEW

**Comment by ehashman** [comment]
Looks like a real test failure:

```
time="2019-09-26T06:36:45Z" level=debug msg="400 Bad Request: Failed to apply request: invalid change   &api.OpenShiftManagedCluster{\n  \tPlan: nil,\n  \tProperties: api.Properties{\n  \t\t... // 10 identical fields\n  \t\tWorkerServicePrincipalProfile: api.ServicePrincipalProfile{ClientID: \"15722dd5-8937-43ba-ac74-312aad33a26a\", Secret: \"af209223-6eda-4e9b-8acf-2b5b331299b5\"},\n  \t\tAzProfile:                     api.AzProfile{TenantID: \"7a1815fb-63ba-4af7-8f33-e7333e421980\", SubscriptionID: \"225e02bc-43d0-43d1-a01a-17e584a4ef69\", ResourceGroup: \"ci-1977-e2e-upgrade-tdnzxj\"},\n  \t\tMonitorProfile: api.MonitorProfile{\n  \t\t\t... // 2 identical fields\n  \t\t\tWorkspaceID:       \"\",\n  \t\t\tWorkspaceKey:      \"\",\n- \t\t\tKeyVaultSecretURL: \"https://kv-inhsoowowkzmwerknslqj.vault.azure.net/secrets/MonitorKey\",\n+ \t\t\tKeyVaultSecretURL: \"\",\n  \t\t},\n  \t\tAPICertProfile: api.CertProfile{KeyVaultSecretURL: \"https://kv-inhsoowowkzmwerknslqj.vault.azure.net/secrets/PublicHostname\"},\n  \t},\n  \tID:   \"/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ci-1977-e2e-upgrade-tdnzxj/providers/Microsoft.ContainerService/openshiftmanagedClusters/ci-1977-e2e-upgrade-tdnzxj\",\n  \tName: \"ci-1977-e2e-upgrade-tdnzxj\",\n  \t... // 4 identical fields\n  }\n" func="pkg/fakerp.(*Server).badRequest()" file="pkg/fakerp/util.go:24"```

**Comment by asalkeld** [comment]
flake https://github.com/openshift/openshift-azure/issues/1775
/retest

**Comment by asalkeld** [comment]
flake https://github.com/openshift/openshift-azure/issues/1631
/retest

**Comment by jim-minter** [comment]
sorry @asalkeld there's a big crossed wire here - I'm not asking for a key vault to be used.  What I'm looking for is for the daemonset to reference a kubernetes secret that we create, such that a person who has the ability to read daemonset objects but not read secrets cannot discover the contents of the secret.

**Comment by asalkeld** [comment]
> sorry @asalkeld there's a big crossed wire here - I'm not asking for a key vault to be used. What I'm looking for is for the daemonset to reference a kubernetes secret that we create, such that a person who has the ability to read daemonset objects but not read secrets cannot discover the contents of the secret.

OK. Oops

**Pull request merged**
