### PR TITLE
don't wait 3 minutes if config blob read fails

### PR DESCRIPTION
**Pull request by jim-minter**
also convert Polls to PollImmediates - saves a few seconds

@kargakis ptal

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@jim-minter there are people in the OWNERS for this that are not assignable to issues here -- are they collaborators on the repo? @sozercan @shrutir25

**Comment by jim-minter** [comment]
good point @stevekuznetsov. #451.

**Comment by mjudeikis** [comment]
lgtm  will leave unti somebody else to check it.

**Pull request merged**
