### PR TITLE
Query VMImage version

### PR DESCRIPTION
**Pull request by gburges**
```release-note
NONE
```

### CODE REVIEW

**Comment by gburges** [comment]
/rerun 

https://github.com/openshift/openshift-azure/issues/2168 flake

**Comment by ehashman** [comment]
I think this is no longer WIP now that tests are passing?

**Comment by gburges** [comment]
> I think this is no longer WIP now that tests are passing?

right, thanks for that

**Comment by ehashman** [comment]
/close

out of scope for now

**Pull request closed without merging**
