### PR TITLE
Rename colons in file names to dashes

### PR DESCRIPTION
**Pull request by sozercan**
As discussed in Slack, this PR renames all file names that include `:` to `-` for Windows development compatibility.

Are there any file content changes needs to be made? I deployed a cluster for testing and everything seemed to deploy fine.

### CODE REVIEW

**Comment by pweil-** [comment]
> Are there any file content changes needs to be made? I deployed a cluster for testing and everything seemed to deploy fine.

looks ok to me too

```
[root@master-000000 cloud-user]# oc get pods --all-namespaces
NAMESPACE                           NAME                                      READY     STATUS    RESTARTS   AGE
default                             docker-registry-654557447b-qf9wz          1/1       Running   0          10m
default                             registry-console-59dd9b597d-4zl4h         1/1       Running   0          10m
default                             router-5c7cf46d6c-gd4dd                   1/1       Running   0          10m
kube-service-catalog                apiserver-75cb7ff9f5-8ncnd                1/1       Running   0          10m
kube-service-catalog                controller-manager-5cf8d8fbf-rsnl9        1/1       Running   0          10m
kube-system                         api-master-000000                         1/1       Running   0          10m
kube-system                         api-master-000001                         1/1       Running   0          10m
kube-system                         api-master-000002                         1/1       Running   0          10m
kube-system                         controllers-master-000000                 1/1       Running   0          10m
kube-system                         controllers-master-000001                 1/1       Running   0          10m
kube-system                         controllers-master-000002                 1/1       Running   0          10m
kube-system                         etcd-master-000000                        1/1       Running   0          10m
kube-system                         etcd-master-000001                        1/1       Running   0          10m
kube-system                         etcd-master-000002                        1/1       Running   0          10m
openshift-ansible-service-broker    asb-9f55fbf56-4kvzk                       1/1       Running   0          10m
openshift-infra                     bootstrap-autoapprover-7b7f695554-cfhrf   1/1       Running   0          10m
openshift-metrics                   prometheus-0                              6/6       Running   0          10m
openshift-metrics                   prometheus-node-exporter-5qkgg            1/1       Running   0          10m
openshift-metrics                   prometheus-node-exporter-5tltj            1/1       Running   0          9m
openshift-metrics                   prometheus-node-exporter-dph7c            1/1       Running   0          10m
openshift-metrics                   prometheus-node-exporter-hcsb4            1/1       Running   0          9m
openshift-metrics                   prometheus-node-exporter-srgzq            1/1       Running   0          10m
openshift-node                      sync-2xf2j                                1/1       Running   0          9m
openshift-node                      sync-7m429                                1/1       Running   0          10m
openshift-node                      sync-hzlx7                                1/1       Running   0          10m
openshift-node                      sync-ps8sk                                1/1       Running   0          10m
openshift-node                      sync-z2sx9                                1/1       Running   0          9m
openshift-sdn                       ovs-94mjm                                 1/1       Running   0          9m
openshift-sdn                       ovs-99gqm                                 1/1       Running   0          9m
openshift-sdn                       ovs-9r6nz                                 1/1       Running   0          10m
openshift-sdn                       ovs-bjq4v                                 1/1       Running   0          10m
openshift-sdn                       ovs-c5lpz                                 1/1       Running   0          10m
openshift-sdn                       sdn-ckclt                                 1/1       Running   0          10m
openshift-sdn                       sdn-gzxkp                                 1/1       Running   0          10m
openshift-sdn                       sdn-h2lgm                                 1/1       Running   0          9m
openshift-sdn                       sdn-l84rc                                 1/1       Running   0          9m
openshift-sdn                       sdn-x24vf                                 1/1       Running   0          10m
openshift-template-service-broker   apiserver-5967db6fc7-gkl2q                1/1       Running   0          10m
openshift-web-console               webconsole-7dddc977ff-cx6l4               1/1       Running   0          10m
```
/lgtm

**Comment by sozercan** [comment]
@pweil- do i need to commit the bindata? or is this good?

**Comment by pweil-** [comment]
@sozercan this prow job has been failing lately, even on non bindata related PRs.  I'll ping someone to take a look in the morning.  I think you're good to go.

**Comment by mjudeikis** [comment]
failures related to https://github.com/openshift/openshift-azure/pull/184

**Comment by jim-minter** [comment]
@sozercan  I pushed up the bindata for you.

/lgtm

**Pull request merged**
