### PR TITLE
Update hash fix

### PR DESCRIPTION
**Pull request by asalkeld**
some small fixes to the logic of updates found during debugging

### CODE REVIEW

**Comment by asalkeld** [comment]
not sure why we are getting this "*update" seems to be empty
```
+ go run cmd/createorupdate/createorupdate.go -rm -use-prod=false -update=test/manifests/normal/create.yaml -update-exec=make e2e -artifact-dir=/tmp/artifacts -artifact-kubeconfig=_data/_out/admin.kubeconfig
time="2018-11-20T08:03:51Z" level=info msg="creating resource group ci-op-7vkr5654-226a1" resourceGroup=ci-op-7vkr5654-226a1
time="2018-11-20T08:03:54Z" level=info msg="starting the fake resource provider" resourceGroup=ci-op-7vkr5654-226a1
time="2018-11-20T08:03:54Z" level=info msg="creating/updating cluster" resourceGroup=ci-op-7vkr5654-226a1
time="2018-11-20T08:03:54Z" level=warning msg="failed parsing the manifest : open : no such file or directory" resourceGroup=ci-op-7vkr5654-226a1
```

**Comment by kargakis** [comment]
@asalkeld seems to started happening ever since we merged your aad changes

See 116 in https://openshift-gce-devel.appspot.com/builds/origin-ci-test/logs/branch-ci-openshift-openshift-azure-master-e2e-azure-upgrade/

**Comment by asalkeld** [comment]
@kargakis I am looking into it

**Pull request merged**
