### PR TITLE
Modifying vmimage script to use the upstream

### PR DESCRIPTION
**Pull request by gburges**
```release-note
NONE
```

### CODE REVIEW

**Comment by ehashman** [comment]
Why are so many v6/v7 bindata files being updated here? That doesn't seem right to me, but verify doesn't seem to be complaining.

**Comment by gburges** [comment]
> Why are so many v6/v7 bindata files being updated here? That doesn't seem right to me, but verify doesn't seem to be complaining.

good question, I _think_ it's the go-bindata pin removal. I saw previously, some (un-)capitalization of words, and rewrites. I left the other PR (1822) as-is if we want to reference the failing verify test there

**Comment by gburges** [comment]
/retest vmimage

quay.io timeout

**Comment by mjudeikis** [comment]
Looks like something is off in the new VM image. need to run locally with this image and check why cluster is not starting.

**Comment by gburges** [comment]
> Looks like something is off in the new VM image. need to run locally with this image and check why cluster is not starting.

Locally it ran successfully

**Comment by y-cote** [comment]
> Why are so many v6/v7 bindata files being updated here? That doesn't seem right to me, but verify doesn't seem to be complaining.

I suspect the use of different go tools would do that.

**Comment by y-cote** [comment]
Tried to verify your PR and hit a flake at the last command of the script it seems with : 

+ az image create -g images -n rhel7-3.11-201908252248 --source   ... 

FATA[2019-08-25T16:57:09-07:00][.../openshift/openshift-azure/cmd/vmimage/vmimage.go:140] main.main() Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded

**Pull request merged**
