### PR TITLE
use property bag for azure client in InitializeCluster

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
manually tested, merging

**Comment by pweil-** [comment]
> manually tested, merging

naughty :oncoming_police_car:

**Comment by jim-minter** [comment]
yes, although in my defence it's blocking msft right now.
shall I stop digging? :-(

**Comment by pweil-** [comment]
no, but shouldn't be skipping CI either :)  Just giving you a hard time, proceed with making this awesome!

**Pull request merged**
