### PR TITLE
remove tenant flag and os.exit(1) from arm scripts

### PR DESCRIPTION
**Pull request by mjudeikis**
```release-note
NONE
```
Remove tenant flag as it causing strange behaviour when tagging images. 
Remove `os.exit(1)` from arm script because none of the validation should produce `os.exit(1)` in the arm scripts. This is causing arm template to fail before results being returned. 
Validation will be added in the follow-up PR

https://coreos.slack.com/archives/CCV9YF9PD/p1565195172015700

### CODE REVIEW

**Comment by ehashman** [comment]
/retest

flake #1356

**Comment by kwoodson** [comment]
@ehashman  @mjudeikis  @m1kola 
The issue with removing this is that we are now passing `vmimage` build when it **_should_** be failing.  There are 2 outstanding issues currently.  The purpose of failing with the python is so that we would not pass unintentionally.

The solution would be to turn them off in the xml file,  document the exceptions by adding them to the rules sheet.  I've basically done that in #1835 

- Configure audispd Plugin To Send Logs To Remote Server
- Encrypt Audit Records Sent With audispd Plugin

**Comment by mjudeikis** [comment]
@kwoodson we should fail CI, and not tag images. What this does currently it - it is failing ARM and we can't even get artefacts because we fail before. We need to move python code into CI and check `/tmp/artifacts` and not in the ARM code script.

**Pull request merged**
