### PR TITLE
Upgrade omsagent to ciprod05262020

### LINKED ISSUE #2300: Update to May release of OMSAgent
Targeted at v19.0 plugin release (wait for v18.0 release to be completed).

See https://github.com/microsoft/OMS-docker/blob/ci_feature_prod/Kubernetes/omsagent.yaml

/assign @olga-mir 
/cc @ganga1980

### PR DESCRIPTION
**Pull request by olga-mir**
```release-note
Upgrade omsagent to ciprod05262020 
```
we skipped April version so this PR is based on diff `ciprod:ciprod03022020` to `ciprod:ciprod05262020`:

https://github.com/microsoft/OMS-docker/compare/f48053862ffb60141ee23f7a9ff2229e43020888..7fa114e0191e379c93a826df360eaf04068691c5#diff-c65ac437f6a64f14b6e97c7963c55fe1

Fixes #2300

### CODE REVIEW

**Comment by ehashman** [comment]
Oops, I'm a little late in the day so I'll review tomorrow, but @mjudeikis do you want this to go into v18 or wait for v19?

**Comment by olga-mir** [comment]
There seems to be a problem with the cluster role. I put this PR in draft while I debug

**Comment by olga-mir** [comment]
cleared the issue above, this should be good to go now

**Comment by ehashman** [comment]
Sorry for the inconvenience @olga-mir, but can you rebase this against the v19 release?

**Comment by olga-mir** [comment]
will do @ehashman

**Comment by olga-mir** [comment]
@ehashman I have updated the PR to target v19. I am creating a cluster right now in order to test it again and will update once it is done. I am not moving this PR to DRAFT and back because it resets the tests once it moves back to ready-for-review

**Comment by olga-mir** [comment]
seems like something is wrong in our environment. I checked some failed tests: 

`400: 400 Bad Request: Failed to apply request: UpdateMasterAgentPoolReimage: compute.VirtualMachineScaleSetVMsClient#Reimage: Failure sending request: StatusCode=400 -- Original Error: Code=\"BadRequest\" Message=\"The VM Instance 0 in Virtual Machine Scale Set ss-master cannot be found.`

**Comment by olga-mir** [comment]
out of 5 failed tests:
2 tests in australiasoutheast and westeurope failed with the above error: `The VM Instance 0 in Virtual Machine Scale Set ss-master cannot be found`
1 test in eastus failed with `context deadline exceeded` flake.
I will send retest in order to see some of the failed clusters in the portal to investigate what happened with VMSS. Running this test on my dev cluster (in australiasoutheast) succeeds. 

/retest

**Comment by ehashman** [comment]
I get this feeling this won't actually succeed on upgrades but let's at least try it.

**Pull request merged**
