### PR TITLE
[wip] azure client consolidation

### PR DESCRIPTION
**Pull request by mjudeikis**
This would consolidate all our azure clients under our interfaces. 
Very similar as done here:
https://github.com/kubernetes/kubernetes/blob/34001d8c6a0ed4edf02d91c5b45920a2676418f9/pkg/cloudprovider/providers/azure/azure_client.go#L773-L814

There are still few places left in upgrade flow to remove.

This would allow testing of those interfaces and reusing same code in tests. For example, etcd backup or cluster init tests would need access to Azure blob client. Which means code duplication again. 

https://github.com/openshift/openshift-azure/issues/400

@jim-minter @kargakis @pweil- wdyt? before I jump to finish this one.

### CODE REVIEW

**Comment by kargakis** [comment]
There is some work that starts on this in https://github.com/openshift/openshift-azure/pull/492

I would ensure no unnecessary client code gets pulled in sync or in the plugin code.

**Comment by mjudeikis** [comment]
> I would ensure no unnecessary client code gets pulled in sync or in the plugin code.

For this I was thinking to keep interfaces and struct separate so if we modify sync pod we add only what is necessary.

**Comment by mjudeikis** [comment]
close in favor: AZURE-148 - Consolidate clients pkg

**Pull request closed without merging**
