### PR TITLE
Revert "Merge pull request #1525 from ehashman/issue-1116"

### PR DESCRIPTION
**Pull request by mjudeikis**
```release-note
Revert 22f6e96 Validation PR
```

ARM validation should cover this

### CODE REVIEW

**Comment by ehashman** [comment]
I think we can close this in favour of #1756 et al.

**Comment by charlesakalugwu** [comment]
@ehashman the content of this PR is different from those in #1756  et al. Are you sure that this should be closed.

**Comment by ehashman** [comment]
@charlesakalugwu yes, it is a different approach to solving the same problem :) We had a discussion during standup and also on Slack weighing the options.

**Pull request closed without merging**
