### PR TITLE
Remove kargakis from OWNERS

### PR DESCRIPTION
**Pull request by kargakis**
/cc @mjudeikis @charlesakalugwu

### CODE REVIEW

**Comment by mjudeikis** [comment]
I will leave this work for @jim-minter to approve. I will not have this on my hand!!!

**Comment by kargakis** [comment]
I need to merge this and update the generated files in release.

**Comment by mjudeikis** [comment]
/lgtm 
:( Im not happy doing this...

**Comment by kargakis** [comment]
wow, you actually did it

**Comment by mjudeikis** [comment]
No mocking please! You know deep inside I want you to come to UK! I need friends to drink beer with!
Now you will have to do PR's as proper upstream developer :D

**Comment by mjudeikis** [comment]
Karma! 
/test e2e

**Comment by jim-minter** [comment]
who lgtm'ed this? :-(

**Comment by mjudeikis** [comment]
> who lgtm'ed this? :-(

I was told my @kargakis. I had no choice... He used violence and psychological pressure.

**Pull request merged**
