### PR TITLE
generate cluster id

### PR DESCRIPTION
**Pull request by pweil-**
Generates 8 digit id and adds them to the end of resource names in the template.

@openshift/sig-azure 
@amanohar FYI

### CODE REVIEW

**Comment by pweil-** [comment]
id

@amanohar ready for your review 

cc @sozercan @shrutir25

**Comment by kargakis** [comment]
Does this change the hostnames in the master VMs?

**Comment by pweil-** [comment]
> Does this change the hostnames in the master VMs?

hmm, I don't think it did, I've been running ssh for every pr to verify node readiness and pod running.  Let me retest that just to be 100% sure

**Comment by pweil-** [comment]
it does 

/hold

**Comment by pweil-** [comment]
this has a lot more knock on effects than anticipated.  Since we've discussed that this is not a blocker I'm going to close for now.  We can revisit if necessary

**Pull request closed without merging**
